### ISSUE TITLE
Uncaught TypeError: Cannot read property 'fixString' of undefined

### ISSUE THREAD

**Issue by DCKT** [AtomLinter/linter-jscs#84] opened 2015-07-30 07:29 UTC
After saving tpl file containing JavaScript in <script> tag

**Atom Version**: 1.0.3
**System**: Unknown Windows Version
**Thrown From**: [linter-jscs](https://github.com/AtomLinter/linter-jscs) package, v2.0.3

### Stack Trace

Uncaught TypeError: Cannot read property 'fixString' of undefined

```
At C:\Users\tdeconinck\AppData\Local\atom\app-1.0.3\resources\app.asar\src\pane.js:801

TypeError: Cannot read property 'fixString' of undefined
    at Function.fixString (C:\Users\tdeconinck\.atom\packages\linter-jscs\index.js:130:40)
    at C:\Users\tdeconinck\.atom\packages\linter-jscs\index.js:36:19
    at Emitter.module.exports.Emitter.emit (C:\Users\tdeconinck\AppData\Local\atom\app-1.0.3\resources\app.asar\node_modules\event-kit\lib\emitter.js:82:11)
    at TextBuffer.module.exports.TextBuffer.saveAs (C:\Users\tdeconinck\AppData\Local\atom\app-1.0.3\resources\app.asar\node_modules\text-buffer\lib\text-buffer.js:995:20)
    at TextBuffer.module.exports.TextBuffer.save (C:\Users\tdeconinck\AppData\Local\atom\app-1.0.3\resources\app.asar\node_modules\text-buffer\lib\text-buffer.js:988:19)
    at TextEditor.module.exports.TextEditor.save (C:\Users\tdeconinck\AppData\Local\atom\app-1.0.3\resources\app.asar\src\text-editor.js:579:26)
    at Pane.module.exports.Pane.saveItem (C:\Users\tdeconinck\AppData\Local\atom\app-1.0.3\resources\app.asar\src\pane.js:539:18)
    at Pane.module.exports.Pane.saveActiveItem (C:\Users\tdeconinck\AppData\Local\atom\app-1.0.3\resources\app.asar\src\pane.js:522:19)
    at Workspace.module.exports.Workspace.saveActivePaneItem (C:\Users\tdeconinck\AppData\Local\atom\app-1.0.3\resources\app.asar\src\workspace.js:609:35)
    at atom-workspace.atom.commands.add.core:save (C:\Users\tdeconinck\AppData\Local\atom\app-1.0.3\resources\app.asar\src\workspace-element.js:293:30)
```

### Commands

```
     -3:55.2.0 project-find:show (atom-text-editor.editor.is-focused)
     -3:54.9.0 core:paste (atom-text-editor.editor.mini.is-focused)
     -3:54 core:confirm (atom-text-editor.editor.mini.is-focused)
     -3:26.8.0 editor:select-to-first-character-of-line (atom-text-editor.editor.is-focused)
     -3:26.5.0 core:backspace (atom-text-editor.editor.is-focused)
     -3:25.9.0 core:move-down (atom-text-editor.editor.is-focused)
     -3:25.6.0 core:backspace (atom-text-editor.editor.is-focused)
     -3:00.3.0 emmet:insert-formatted-line-break-only (atom-text-editor.editor.is-focused)
     -3:00.3.0 editor:newline (atom-text-editor.editor.is-focused)
  4x -2:52.9.0 core:backspace (atom-text-editor.editor.is-focused)
     -2:42 core:save (atom-text-editor.editor.is-focused)
     -2:30.4.0 fuzzy-finder:toggle-file-finder (atom-text-editor.editor.is-focused)
     -2:26.3.0 editor:consolidate-selections (atom-text-editor.editor.mini.is-focused)
     -2:26.3.0 core:cancel (atom-text-editor.editor.mini.is-focused)
     -2:21.2.0 settings-view:check-for-package-updates (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui.find-visible)
  4x -2:05.6.0 core:save (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "ignoredNames": [
      "*.scssc"
    ]
  },
  "linter-jscs": {
    "fixOnSave": true
  }
}
```

### Installed Packages

```coffee
# User
emmet, v2.3.12
language-cshtml, v0.1.1
linter, v1.2.4
linter-jscs, v2.0.3

# Dev
No dev packages
```

**Comment by DCKT** [comment] 2015-07-30 07:31
**Atom Version**: 1.0.3
**System**: Unknown Windows Version
**Thrown From**: [linter-jscs](https://github.com/AtomLinter/linter-jscs) package, v2.0.3


### Stack Trace

Uncaught TypeError: Cannot read property 'fixString' of undefined

```
At C:\Users\tdeconinck\AppData\Local\atom\app-1.0.3\resources\app.asar\src\pane.js:801

TypeError: Cannot read property 'fixString' of undefined
    at Function.fixString (C:\Users\tdeconinck\.atom\packages\linter-jscs\index.js:130:40)
    at C:\Users\tdeconinck\.atom\packages\linter-jscs\index.js:36:19
    at Emitter.module.exports.Emitter.emit (C:\Users\tdeconinck\AppData\Local\atom\app-1.0.3\resources\app.asar\node_modules\event-kit\lib\emitter.js:82:11)
    at TextBuffer.module.exports.TextBuffer.saveAs (C:\Users\tdeconinck\AppData\Local\atom\app-1.0.3\resources\app.asar\node_modules\text-buffer\lib\text-buffer.js:995:20)
    at TextBuffer.module.exports.TextBuffer.save (C:\Users\tdeconinck\AppData\Local\atom\app-1.0.3\resources\app.asar\node_modules\text-buffer\lib\text-buffer.js:988:19)
    at TextEditor.module.exports.TextEditor.save (C:\Users\tdeconinck\AppData\Local\atom\app-1.0.3\resources\app.asar\src\text-editor.js:579:26)
    at Pane.module.exports.Pane.saveItem (C:\Users\tdeconinck\AppData\Local\atom\app-1.0.3\resources\app.asar\src\pane.js:539:18)
    at Pane.module.exports.Pane.saveActiveItem (C:\Users\tdeconinck\AppData\Local\atom\app-1.0.3\resources\app.asar\src\pane.js:522:19)
    at Workspace.module.exports.Workspace.saveActivePaneItem (C:\Users\tdeconinck\AppData\Local\atom\app-1.0.3\resources\app.asar\src\workspace.js:609:35)
    at atom-workspace.atom.commands.add.core:save (C:\Users\tdeconinck\AppData\Local\atom\app-1.0.3\resources\app.asar\src\workspace-element.js:293:30)
```

### Commands

```
     -3:55.2.0 project-find:show (atom-text-editor.editor.is-focused)
     -3:54.9.0 core:paste (atom-text-editor.editor.mini.is-focused)
     -3:54 core:confirm (atom-text-editor.editor.mini.is-focused)
     -3:26.8.0 editor:select-to-first-character-of-line (atom-text-editor.editor.is-focused)
     -3:26.5.0 core:backspace (atom-text-editor.editor.is-focused)
     -3:25.9.0 core:move-down (atom-text-editor.editor.is-focused)
     -3:25.6.0 core:backspace (atom-text-editor.editor.is-focused)
     -3:00.3.0 emmet:insert-formatted-line-break-only (atom-text-editor.editor.is-focused)
     -3:00.3.0 editor:newline (atom-text-editor.editor.is-focused)
  4x -2:52.9.0 core:backspace (atom-text-editor.editor.is-focused)
     -2:42 core:save (atom-text-editor.editor.is-focused)
     -2:30.4.0 fuzzy-finder:toggle-file-finder (atom-text-editor.editor.is-focused)
     -2:26.3.0 editor:consolidate-selections (atom-text-editor.editor.mini.is-focused)
     -2:26.3.0 core:cancel (atom-text-editor.editor.mini.is-focused)
     -2:21.2.0 settings-view:check-for-package-updates (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui.find-visible)
  4x -2:05.6.0 core:save (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "ignoredNames": [
      "*.scssc"
    ]
  },
  "linter-jscs": {
    "fixOnSave": true
  }
}
```

### Installed Packages

```coffee
# User
emmet, v2.3.12
language-cshtml, v0.1.1
linter, v1.2.4
linter-jscs, v2.0.3

# Dev
No dev packages
```

**Comment by adamzerner** [comment] 2015-07-30 20:08
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.0.3
**System**: Mac OS X 10.10.4
**Thrown From**: [linter-jscs](https://github.com/AtomLinter/linter-jscs) package, v2.0.4


### Stack Trace

Uncaught TypeError: Cannot read property 'fixString' of undefined

```
At /Users/azerner/Downloads/Atom.app/Contents/Resources/app.asar/src/pane.js:801

TypeError: Cannot read property 'fixString' of undefined
  at Function.fixString (/Users/azerner/.atom/packages/linter-jscs/index.js:156:40)
  at /Users/azerner/.atom/packages/linter-jscs/index.js:40:19
  at Emitter.module.exports.Emitter.emit (/Users/azerner/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at TextBuffer.module.exports.TextBuffer.saveAs (/Users/azerner/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:995:20)
  at TextBuffer.module.exports.TextBuffer.save (/Users/azerner/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:988:19)
  at TextEditor.module.exports.TextEditor.save (/Users/azerner/Downloads/Atom.app/Contents/Resources/app.asar/src/text-editor.js:579:26)
  at Pane.module.exports.Pane.saveItem (/Users/azerner/Downloads/Atom.app/Contents/Resources/app.asar/src/pane.js:539:18)
  at Pane.module.exports.Pane.saveActiveItem (/Users/azerner/Downloads/Atom.app/Contents/Resources/app.asar/src/pane.js:522:19)
  at Workspace.module.exports.Workspace.saveActivePaneItem (/Users/azerner/Downloads/Atom.app/Contents/Resources/app.asar/src/workspace.js:609:35)
  at atom-workspace.atom.commands.add.core:save (/Users/azerner/Downloads/Atom.app/Contents/Resources/app.asar/src/workspace-element.js:293:30)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Users/azerner/Downloads/Atom.app/Contents/Resources/app.asar/src/command-registry.js:241:29)
  at /Users/azerner/Downloads/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Users/azerner/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:524:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Users/azerner/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:347:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/Users/azerner/Downloads/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:177:20)

```

### Commands

```
     -0:03.1.0 emmet:insert-formatted-line-break-only (atom-text-editor.editor.is-focused)
     -0:03.1.0 editor:newline (atom-text-editor.editor.is-focused)
     -0:02.2.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:01.2.0 core:save (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "atom-pair"
    ]
  },
  "linter-jscs": {
    "harmony": true,
    "executablePath": "/usr/local/bin/jscs",
    "esnext": true,
    "fixOnSave": true
  }
}
```

### Installed Packages

```coffee
# User
angularjs, v0.3.0
atom-beautify, v0.28.8
editorconfig, v1.0.1
emmet, v2.3.12
file-icons, v1.5.8
language-javascript-jsx, v0.3.7
linter, v1.2.4
linter-htmlhint, v0.0.17
linter-jscs, v2.0.4
linter-scss-lint, v2.0.0
minimap, v4.12.1
minimap-git-diff, v4.1.7
tab-control, v0.6.7
white-cursor, v0.6.0

# Dev
No dev packages
```

**Comment by xream** [comment] 2015-07-31 13:24
Same error message here with language-babel.

After disabled  language-babel, this error is gone.

**Comment by anonrig** [comment] 2015-08-13 15:48
+1

**Comment by anonrig** [comment] 2015-08-13 15:49
**Atom Version**: 1.0.3
**System**: Mac OS X 10.90.1
**Thrown From**: [linter-jscs](https://github.com/AtomLinter/linter-jscs) package, v2.0.4


### Stack Trace

Uncaught TypeError: Cannot read property 'fixString' of undefined

```
At /Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:801

TypeError: Cannot read property 'fixString' of undefined
    at Function.fixString (/Users/yagiz/.atom/packages/linter-jscs/index.js:156:40)
    at /Users/yagiz/.atom/packages/linter-jscs/index.js:40:19
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
    at TextBuffer.module.exports.TextBuffer.saveAs (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:995:20)
    at TextBuffer.module.exports.TextBuffer.save (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:988:19)
    at TextEditor.module.exports.TextEditor.save (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:579:26)
    at Pane.module.exports.Pane.saveItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:539:18)
    at Pane.module.exports.Pane.saveActiveItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:522:19)
    at Workspace.module.exports.Workspace.saveActivePaneItem (/Applications/Atom.app/Contents/Resources/app.asar/src/workspace.js:609:35)
    at atom-workspace.atom.commands.add.core:save (/Applications/Atom.app/Contents/Resources/app.asar/src/workspace-element.js:293:30)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:241:29)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:524:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:347:22)
    at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:177:20)
```

### Commands

```
     -1:50.9.0 core:save (atom-text-editor.editor.is-focused)
     -1:45.8.0 core:copy (atom-notification.fatal.icon.icon-bug.native-key-bindings.has-detail.has-close.has-stack)
     -1:25.5.0 window:update-available (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-dark-syntax.theme-atom-dark-ui)
  7x -1:08.6.0 core:save (atom-text-editor.editor.is-focused)
     -1:04.4.0 core:close (atom-text-editor.editor.is-focused)
     -0:32.2.0 core:save (a.)
  2x -0:11.5.0 core:undo (atom-text-editor.editor.is-focused)
     -0:09.9.0 core:close (atom-text-editor.editor.is-focused)
  2x -0:07.6.0 core:save (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "one-dark-syntax"
    ],
    "disabledPackages": [
      "linter"
    ]
  },
  "linter-jscs": {
    "preset": "google",
    "harmony": true,
    "messageType": "warning",
    "fixOnSave": true
  }
}
```

### Installed Packages

```coffee
# User
editorconfig, v1.0.1
file-icons, v1.6.3
linter-jscs, v2.0.4
wakatime, v4.0.12

# Dev
No dev packages
```

**Comment by cage1016** [comment] 2015-08-14 06:15
**Atom Version**: 1.0.7
**System**: Mac OS X 10.10.4
**Thrown From**: [linter-jscs](https://github.com/AtomLinter/linter-jscs) package, v2.0.4


### Stack Trace

Uncaught TypeError: Cannot read property 'fixString' of undefined

```
At /Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:801

TypeError: Cannot read property 'fixString' of undefined
    at Function.fixString (/Users/cage/.atom/packages/linter-jscs/index.js:156:40)
    at /Users/cage/.atom/packages/linter-jscs/index.js:40:19
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
    at TextBuffer.module.exports.TextBuffer.saveAs (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1000:20)
    at TextBuffer.module.exports.TextBuffer.save (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:992:19)
    at TextEditor.module.exports.TextEditor.save (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:579:26)
    at Pane.module.exports.Pane.saveItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:539:18)
    at Pane.module.exports.Pane.saveActiveItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:522:19)
    at Workspace.module.exports.Workspace.saveActivePaneItem (/Applications/Atom.app/Contents/Resources/app.asar/src/workspace.js:609:35)
    at atom-workspace.atom.commands.add.core:save (/Applications/Atom.app/Contents/Resources/app.asar/src/workspace-element.js:293:30)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:241:29)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:524:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:347:22)
    at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:177:20)
```

### Commands

```
  4x -2:22.5.0 core:save (atom-text-editor.editor.is-focused)
  2x -2:16.7.0 editor:newline (atom-text-editor.editor.is-focused)
     -2:15 core:save (atom-text-editor.editor.is-focused)
  2x -2:14 editor:newline (atom-text-editor.editor.is-focused)
     -2:12.7.0 editor:consolidate-selections (atom-text-editor.editor.is-focused)
     -2:12.7.0 core:cancel (atom-text-editor.editor.is-focused)
     -2:11.4.0 core:save (atom-text-editor.editor.is-focused)
     -0:32.2.0 editor:consolidate-selections (atom-text-editor.editor.is-focused)
     -0:32.2.0 core:cancel (atom-text-editor.editor.is-focused)
     -0:00.7.0 core:save (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "one-dark-ui",
      "monokai-seti"
    ]
  },
  "linter-jscs": {
    "esnext": true,
    "preset": "node-style-guide",
    "fixOnSave": true
  }
}
```

### Installed Packages

```coffee
# User
atom-beautify, v0.28.11
auto-update-packages, v1.0.0
file-icons, v1.6.3
go-plus, v3.4.5
go-rename, v0.3.0
highlight-selected, v0.10.1
language-docker, v1.1.3
language-gitignore, v0.2.0
language-protobuf, v0.5.0
language-shellscript, v0.15.0
linter, v1.3.4
linter-jscs, v2.0.4
minimap, v4.12.3
monokai-seti, v0.7.0
project-manager, v1.15.11

# Dev
No dev packages
```

**Comment by antipodeman** [comment] 2015-09-11 08:29
+1
Same problem

**Comment by scottmcpherson** [comment] 2015-09-14 19:51
+1

**Comment by acusti** [comment] 2015-09-15 19:18
I believe this is fixed. Can anyone who has previously experienced this problem confirm if it’s fixed for them after upgrading to linter-jscs@3.0.0 (and restarting the editor)?

**Comment by scottmcpherson** [comment] 2015-09-15 22:06
Thanks @acusti !

So far so good with 3.0.0.

**Comment by cage1016** [comment] 2015-10-04 05:55
@acusti The problem is gone after update to 3.0.0

Thanks a lot.

**Comment by donflopez** [comment] 2015-10-14 13:23
I have the same error and I can't see the errors on my code.

1. Install jscs
2. Save a js file

**Atom Version**: 1.0.18
**System**: Mac OS X 10.10.5
**Thrown From**: [linter-jscs](https://github.com/AtomLinter/linter-jscs) package, v3.1.1


### Stack Trace

Uncaught TypeError: Cannot read property 'fixString' of undefined

```
At /Users/donflopez/.atom/packages/linter-jscs/index.js:138

TypeError: Cannot read property 'fixString' of undefined
  at Function.fixString (/Users/donflopez/.atom/packages/linter-jscs/index.js:114:32)
  at /Users/donflopez/.atom/packages/linter-jscs/index.js:40:21
  at doNTCallback0 (node.js:416:9)
  at process._tickDomainCallback (node.js:386:13)

```

### Commands

```
  2x -2:13.3.0 core:move-down (atom-text-editor.editor.mini.is-focused)
     -2:12.8.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -2:09.6.0 core:backspace (atom-text-editor.editor.is-focused)
  2x -2:09.4.0 core:save (atom-text-editor.editor.is-focused)
     -2:06.1.0 settings-view:open (atom-text-editor.editor.is-focused)
  3x -1:51.9.0 core:save (div.settings-view.pane-item)
     -1:32.9.0 settings-view:open (atom-text-editor.editor.is-focused)
 21x -1:28.6.0 core:save (atom-text-editor.editor.is-focused)
     -1:14.8.0 core:backspace (atom-text-editor.editor.is-focused)
  3x -1:14.4.0 core:save (atom-text-editor.editor.is-focused)
     -1:12 core:backspace (atom-text-editor.editor.is-focused)
     -1:11.7.0 core:save (atom-text-editor.editor.is-focused)
     -1:10.3.0 core:backspace (atom-text-editor.editor.is-focused)
     -1:09.5.0 core:save (atom-text-editor.editor.is-focused)
  2x -0:37.1.0 core:backspace (div.settings-view.pane-item)
     -0:01.1.0 core:save (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "minimap"
    ]
  },
  "linter-jscs": {
    "displayAs": "jscs Error",
    "preset": "idiomatic",
    "fixOnSave": true
  }
}
```

### Installed Packages

```coffee
# User
color-picker, v2.0.12
css-color-underline, v1.0.1
docblockr, v0.7.3
emmet, v2.3.13
linter-jscs, v3.1.1
node-debugger, v1.1.8

# Dev
No dev packages
```

**Comment by sstefoss** [comment] 2015-10-27 13:41
Encountered the same problem today:

1. Install jscs
2. Save js file

**Atom Version**: 1.0.19
**System**: Mac OS X 10.11.1
**Thrown From**: [linter-jscs](https://github.com/AtomLinter/linter-jscs) package, v3.1.2


### Stack Trace

Uncaught TypeError: Cannot read property 'fixString' of undefined

```
At /Users/stef/.atom/packages/linter-jscs/index.js:138

TypeError: Cannot read property 'fixString' of undefined
  at Function.fixString (/Users/stef/.atom/packages/linter-jscs/index.js:114:32)
  at /Users/stef/.atom/packages/linter-jscs/index.js:40:21
  at doNTCallback0 (node.js:416:9)
  at process._tickCallback (node.js:345:13)

```

### Commands

```
  2x -0:56.3.0 core:save (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -0:53.9.0 core:backspace (atom-text-editor.editor.is-focused)
  3x -0:53.7.0 core:save (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "linter"
    ]
  },
  "linter-jscs": {
    "esnext": true,
    "fixOnSave": true
  }
}
```

### Installed Packages

```coffee
# User
language-babel, v0.15.10
linter-jscs, v3.1.2
react, v0.12.10

# Dev
No dev packages
```

**Comment by casesandberg** [comment] 2016-01-17 23:08
Can you update `atom` and `linter-jscs` and see if this is still an issue?

**Comment by casesandberg** [comment] 2016-02-02 18:56
Marking as closed as I can not reproduce this. If you are still having issues please re-open.

**Closed by casesandberg** 2016-02-02 18:56 UTC
Labels: can't reproduce
