### ISSUE TITLE
Fix Not Working

### ISSUE THREAD

**Issue by eighteyes** [AtomLinter/linter-jscs#81] opened 2015-07-29 21:48 UTC
Probably a dupe.

1. Turn on Fix on Save
2. Try to save JS file

**Atom Version**: 1.0.3
**System**: Mac OS X 10.10.4
**Thrown From**: [linter-jscs](https://github.com/AtomLinter/linter-jscs) package, v2.0.3

### Stack Trace

Uncaught TypeError: Cannot read property 'fixString' of undefined

```
At /Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:801

TypeError: Cannot read property 'fixString' of undefined
  at Function.fixString (/Users/god/.atom/packages/linter-jscs/index.js:155:40)
  at /Users/god/.atom/packages/linter-jscs/index.js:40:19
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at TextBuffer.module.exports.TextBuffer.saveAs (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:995:20)
  at TextBuffer.module.exports.TextBuffer.save (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:988:19)
  at TextEditor.module.exports.TextEditor.save (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:579:26)
  at Pane.module.exports.Pane.saveItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:539:18)
  at Pane.module.exports.Pane.saveActiveItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:522:19)
  at Workspace.module.exports.Workspace.saveActivePaneItem (/Applications/Atom.app/Contents/Resources/app.asar/src/workspace.js:609:35)
  at atom-workspace.atom.commands.add.core:save (/Applications/Atom.app/Contents/Resources/app.asar/src/workspace-element.js:293:30)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:241:29)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:524:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:347:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:177:20)

```

### Commands

```
     -2:50.5.0 core:close (input#linter-jscs.fixOnSave.)
     -2:47.7.0 core:save (atom-text-editor.editor.is-focused)
  3x -1:36.9.0 core:backspace (atom-text-editor.editor.is-focused)
     -1:33.6.0 core:save (atom-text-editor.editor.is-focused)
     -1:31.8.0 editor:consolidate-selections (atom-text-editor.editor.is-focused)
     -1:31.8.0 core:cancel (atom-text-editor.editor.is-focused)
     -1:29.6.0 settings-view:open (atom-text-editor.editor.is-focused)
     -0:02.0 core:save (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "audioBeep": false,
    "themes": [
      "one-dark-ui",
      "base16-tomorrow-dark-theme"
    ],
    "disabledPackages": [
      "npm-docs",
      "node-resolver",
      "linter-tidy",
      "linter-tidy",
      "npm-docs",
      "welcome",
      "language-c",
      "language-clojure",
      "language-csharp",
      "language-mustache",
      "language-java",
      "language-objective-c",
      "language-perl",
      "language-php",
      "language-ruby-on-rails",
      "language-sql",
      "language-toml",
      "language-xml"
    ]
  },
  "linter-jscs": {
    "verbose": true,
    "displayAs": "warning",
    "fixOnSave": true
  }
}
```

### Installed Packages

```coffee
# User
angularjs, v0.3.0
atom-beautify, v0.28.8
atomatigit, v1.5.3
auto-indent, v0.5.0
autocomplete-modules, v1.0.0
emmet, v2.3.12
figlet, v0.4.0
gulp-snippets, v0.6.1
indent-guide-improved, v1.4.1
language-html, v0.40.0
linter, v1.2.4
linter-jscs, v2.0.3
linter-jshint, v1.1.4
mocha, v0.0.7
node-debugger, v1.1.7
pigments, v0.9.2
react, v0.12.6

# Dev
No dev packages
```

**Comment by Arcanemagus** [comment] 2015-12-02 22:16
This was reported before, but it seems all the discussion went into #84, so I'm marking this as a duplicate of that.

**Closed by Arcanemagus** 2015-12-02 22:16 UTC
