### ISSUE TITLE
Column start greater than line length

### ISSUE THREAD

**Issue by pascalpp** [AtomLinter/linter-jscs#239] opened 2016-05-09 18:30 UTC
### Version
4.0.0

### Issue
Similar to https://github.com/AtomLinter/linter-jscs/issues/167

I'm getting "Error: Column start (2) greater than line length (0)" with a very simple .jscsrc config:

```
{
    "validateIndentation": 4,
    "validateNewlineAfterArrayElements": {
        "maximum": 4
    }
}
```

If I remove that second rule, `validateNewlineAfterArrayElements`, the error no longer occurs..

Full trace:

```
Error: Column start (2) greater than line length (0)
    at Object.rangeFromLineNumber (/Users/pascal/.atom/packages/linter-eslint/node_modules/atom-linter/lib/index.js:194:11)
    at /Users/pascal/.atom/packages/linter-jscs/src/linter-jscs.js:184:33
    at Array.map (native)
    at Object.lint (/Users/pascal/.atom/packages/linter-jscs/src/linter-jscs.js:179:39)
    at promises.push.Promise.then._this.emitter.emit.linter (/Users/pascal/.atom/packages/linter/lib/linter-registry.js:63:26)
    at /Users/pascal/.atom/packages/linter/lib/linter-registry.js:62:23
    at Set.forEach (native)
    at LinterRegistry.lint (/Users/pascal/.atom/packages/linter/lib/linter-registry.js:60:18)
    at /Users/pascal/.atom/packages/linter/lib/linter.coffee:98:16
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at /Users/pascal/.atom/packages/linter/lib/editor-linter.js:80:22
    at /Users/pascal/.atom/packages/linter/lib/helpers.coffee:23:18
```

**Comment by Arcanemagus** [comment] 2016-05-09 18:33
Are you able to share the file you are seeing this on?

**Comment by pascalpp** [comment] 2016-05-09 18:41
i can reproduce with a very simple file that only contains:
```
var bar = [1, 2, 3, 4, 5, 6]
```

**Comment by pascalpp** [comment] 2016-05-09 18:46
This also occurs with a more complex config which uses `"preset": "airbnb"` and some override rules. If I remove the `validateNewlineAfterArrayElements` rule it stops erroring. So must be something related to that rule. Will see if I can track it down.

**Comment by pascalpp** [comment] 2016-05-09 19:02
Disabled linter-eslint to isolate the issue. Still occurs with just linter-jscs enabled.

```
Error: Column start (1) greater than line length (0)
    at Object.rangeFromLineNumber (/Users/pascal/.atom/packages/linter-jscs/node_modules/atom-linter/lib/index.js:194:11)
    at /Users/pascal/.atom/packages/linter-jscs/src/linter-jscs.js:184:33
    at Array.map (native)
    at Object.lint (/Users/pascal/.atom/packages/linter-jscs/src/linter-jscs.js:179:39)
    at promises.push.Promise.then._this.emitter.emit.linter (/Users/pascal/.atom/packages/linter/lib/linter-registry.js:63:26)
    at /Users/pascal/.atom/packages/linter/lib/linter-registry.js:62:23
    at Set.forEach (native)
    at LinterRegistry.lint (/Users/pascal/.atom/packages/linter/lib/linter-registry.js:60:18)
    at /Users/pascal/.atom/packages/linter/lib/linter.coffee:98:16
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at /Users/pascal/.atom/packages/linter/lib/editor-linter.js:80:22
    at /Users/pascal/.atom/packages/linter/lib/helpers.coffee:23:18
```

(I know this is a bit of a dead end with jscs merging with eslint. But I'm hoping to continue using jscs to fix some things that eslint doesn't fix yet, until eslint's rules gets some fixer updates.)

**Comment by Arcanemagus** [comment] 2016-05-09 19:05
It looks like that rule is horribly broken with that code:
![image](https://cloud.githubusercontent.com/assets/427137/15124676/0c10f2c4-15de-11e6-96f6-7c52f28f76f8.png)

Tested with this folder setup: [linter-jscs_GH239.zip](https://github.com/AtomLinter/linter-jscs/files/255687/linter-jscs_GH239.zip)

As this is confirmed to be a bug in `jscs` itself, the next step is to file a bug over there (They are still working on it, the final shutdown isn't for a while from now :wink:). Do you want me to file that or do you want to track it?

**Comment by pascalpp** [comment] 2016-05-09 19:11
oh nice, thanks! yeah could you open the bug and link it here?

**Comment by pascalpp** [comment] 2016-05-09 19:14
might be related to https://github.com/jscs-dev/node-jscs/issues/2219 ?

**Comment by Arcanemagus** [comment] 2016-05-09 20:51
Possibly, I'm guessing that is just a symptom of the rules not parsing the new CST properly though. I'll file it over there and let the maintainers decide if it's a duplicate since I don't know the internals enough to say for sure.

**Comment by Arcanemagus** [comment] 2016-05-09 21:00
Filed the above issue, let's see what they say.

**Comment by Arcanemagus** [comment] 2016-05-27 16:40
Closing as fixed in https://github.com/jscs-dev/node-jscs/pull/2252.

**Closed by Arcanemagus** 2016-05-27 16:40 UTC
Labels: External
