### ISSUE TITLE
Failed to load the linter-jscs package

### ISSUE THREAD

**Issue by armendarabyan** [AtomLinter/linter-jscs#92] opened 2015-08-16 00:32 UTC
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.0.7
**System**: Mac OS X 10.10.3
**Thrown From**: [linter-jscs](https://github.com/AtomLinter/linter-jscs) package, v2.0.4

### Stack Trace

Failed to load the linter-jscs package

```
At Cannot find module 'concat-map'

Error: Cannot find module 'concat-map'
  at Module._resolveFilename (module.js:328:15)
  at Function.Module._resolveFilename (/Applications/Atom.app/Contents/Resources/app.asar/src/module-cache.js:383:52)
  at Function.Module._load (module.js:270:25)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at Object.<anonymous> (/Users/armendarabyan/.atom/packages/linter-jscs/node_modules/jscs/node_modules/minimatch/node_modules/brace-expansion/index.js:1:79)
  at Module._compile (module.js:452:26)
  at Object.loadFile [as .js] (/Applications/Atom.app/Contents/Resources/app.asar/src/babel.js:163:21)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at Object.<anonymous> (/Users/armendarabyan/.atom/packages/linter-jscs/node_modules/jscs/node_modules/minimatch/minimatch.js:10:14)
  at Module._compile (module.js:452:26)
  at Object.loadFile [as .js] (/Applications/Atom.app/Contents/Resources/app.asar/src/babel.js:163:21)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at Object.<anonymous> (/Users/armendarabyan/.atom/packages/linter-jscs/node_modules/jscs/node_modules/vow-fs/node_modules/glob/glob.js:44:17)
  at Module._compile (module.js:452:26)
  at Object.loadFile [as .js] (/Applications/Atom.app/Contents/Resources/app.asar/src/babel.js:163:21)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at Object.<anonymous> (/Users/armendarabyan/.atom/packages/linter-jscs/node_modules/jscs/node_modules/vow-fs/lib/fs.js:18:12)
  at Module._compile (module.js:452:26)
  at Object.loadFile [as .js] (/Applications/Atom.app/Contents/Resources/app.asar/src/babel.js:163:21)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at Object.<anonymous> (/Users/armendarabyan/.atom/packages/linter-jscs/node_modules/jscs/lib/checker.js:1:75)
  at Module._compile (module.js:452:26)
  at Object.loadFile [as .js] (/Applications/Atom.app/Contents/Resources/app.asar/src/babel.js:163:21)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at Object.<anonymous> (/Users/armendarabyan/.atom/packages/linter-jscs/index.js:11:13)
  at Module._compile (module.js:452:26)
  at Object.loadFile [as .js] (/Applications/Atom.app/Contents/Resources/app.asar/src/babel.js:167:19)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at Package.module.exports.Package.requireMainModule (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:759:34)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:190:28
  at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:167:15)
  at Package.module.exports.Package.load (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:181:12)
  at PackageManager.module.exports.PackageManager.loadPackage (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:405:14)
  at PackageManager.module.exports.PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:485:30)
  at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-manager.js:370:29
  at exit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-manager.js:59:16)
  at triggerExitCallback (/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:213:47)
  at ChildProcess.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:235:18)
  at emitTwo (events.js:87:13)
  at ChildProcess.emit (events.js:169:7)
  at Process.ChildProcess._handle.onexit (child_process.js:1057:12)

```

### Commands

```
     -0:03.0 editor:delete-to-beginning-of-line (atom-text-editor.editor.mini.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "laravel",
      "laravel-facades",
      "deprecation-cop",
      "file-icons",
      "atom-bootstrap3",
      "travis-ci-status",
      "Zen",
      "editor-stats",
      "command-logger",
      "git-diff-details",
      "color-picker",
      "angularjs-boilerplate-snippets"
    ]
  }
}
```

### Installed Packages

```coffee
# User
angularjs, v0.3.0
angularjs-styleguide-snippets, v0.7.2
emmet, v2.3.12
linter-jscs, v2.0.4
minimap, v4.12.1
vim-mode, v0.57.0

# Dev
No dev packages
```

**Comment by Samsinite** [comment] 2015-09-02 19:04
Getting this error as well immediately after updating the linter-jscs package.

**Comment by Eschon** [comment] 2015-09-03 08:00
From your installed packages it seems like you don't have the `linter` package installed.
Try installing it first, even if that is not the cause of this error `linter-jscs` won't work without it.

**Comment by Samsinite** [comment] 2015-09-03 15:07
linter is installed and up to date, not the issue.

**Comment by Samsinite** [comment] 2015-09-03 15:08
My stack trace is slightly different though:

```
Cannot find module 'vow-fs'
Hide Stack Trace
Error: Cannot find module 'vow-fs'
    at Module._resolveFilename (module.js:328:15)
    at Function.Module._resolveFilename (/Applications/Atom.app/Contents/Resources/app.asar/src/module-cache.js:383:52)
    at Function.Module._load (module.js:270:25)
    at Module.require (module.js:357:17)
    at require (module.js:376:17)
    at Object.<anonymous> (/Users/sam/.atom/packages/linter-jscs/node_modules/jscs/lib/checker.js:1:75)
    at Module._compile (module.js:452:26)
    at Object.defineProperty.value [as .js] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:169:21)
    at Module.load (module.js:347:32)
    at Function.Module._load (module.js:302:12)
    at Module.require (module.js:357:17)
    at require (module.js:376:17)
    at Object.<anonymous> (/Users/sam/.atom/packages/linter-jscs/index.js:11:13)
    at Module._compile (module.js:452:26)
    at Object.defineProperty.value [as .js] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:169:21)
    at Module.load (module.js:347:32)
```

**Comment by Eschon** [comment] 2015-09-04 08:41
If your stack trace is different you might wan't to open a separate issue with the full information (config, installed packages, ...).

**Comment by imalitavakoli** [comment] 2015-09-21 07:32
I have the same issue...
But mine says:
```
Error: Cannot find module 'jscs/lib/cli-config'
    at Module._resolveFilename (module.js:334:15)
    at Function.Module._resolveFilename (C:\Users\Ali\AppData\Local\atom\app-1.0.15\resources\app.asar\src\module-cache.js:383:52)
    at Function.Module._load (module.js:284:25)
    at Module.require (module.js:363:17)
    at require (module.js:382:17)
    at Object.<anonymous> (C:/Users/Ali/.atom/packages/linter-jscs/index.js:3:24)
    at Module._compile (module.js:428:26)
    at Object.defineProperty.value [as .js] (C:\Users\Ali\AppData\Local\atom\app-1.0.15\resources\app.asar\src\compile-cache.js:169:21)
    at Module.load (module.js:353:32)
    at Function.Module._load (module.js:308:12)
```

**Comment by casesandberg** [comment] 2016-01-17 20:03
Are you still having this issue?

**Comment by casesandberg** [comment] 2016-02-02 18:57
Marking as closed as I can not reproduce this. If you are still having issues please re-open.

**Closed by casesandberg** 2016-02-02 18:57 UTC
Labels: can't reproduce

**Comment by NullVoxPopuli** [comment] 2016-04-25 00:08
I'm still having issues :-(

[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.187.0
**System**: linux 4.2.0-35-generic
**Thrown From**: [linter-jscs](https://github.com/AtomLinter/linter-jscs) package, v3.5.0

### Stack Trace

Failed to load the linter-jscs package

```
At /home/lprestonsegoiii/.atom/packages/linter-jscs/src/linter-jscs.js: Unexpected token (13:16)
  11 | 
  12 | export default class LinterJSCS {
> 13 |   static config = {
     |                 ^
  14 |     preset: {
  15 |       title: 'Preset',
  16 |       description: 'Preset option is ignored if a config file is found for the linter.',

SyntaxError: /home/lprestonsegoiii/.atom/packages/linter-jscs/src/linter-jscs.js: Unexpected token (13:16)
  11 | 
  12 | export default class LinterJSCS {
> 13 |   static config = {
     |                 ^
  14 |     preset: {
  15 |       title: 'Preset',
  16 |       description: 'Preset option is ignored if a config file is found for the linter.',
    at raise (/usr/share/atom/resources/app/node_modules/babel-core/node_modules/acorn-babel/acorn_csp.js:343:15)
    at unexpected (/usr/share/atom/resources/app/node_modules/babel-core/node_modules/acorn-babel/acorn_csp.js:2278:5)
    at expect (/usr/share/atom/resources/app/node_modules/babel-core/node_modules/acorn-babel/acorn_csp.js:2266:18)
    at parseFunctionParams (/usr/share/atom/resources/app/node_modules/babel-core/node_modules/acorn-babel/acorn_csp.js:3571:5)
    at parseMethod (/usr/share/atom/resources/app/node_modules/babel-core/node_modules/acorn-babel/acorn_csp.js:3558:5)
    at parseClass (/usr/share/atom/resources/app/node_modules/babel-core/node_modules/acorn-babel/acorn_csp.js:3703:24)
    at parseExprAtom (/usr/share/atom/resources/app/node_modules/babel-core/node_modules/acorn-babel/acorn_csp.js:3266:14)
    at parseExprSubscripts (/usr/share/atom/resources/app/node_modules/babel-core/node_modules/acorn-babel/acorn_csp.js:3117:16)
    at parseMaybeUnary (/usr/share/atom/resources/app/node_modules/babel-core/node_modules/acorn-babel/acorn_csp.js:3099:16)
    at parseExprOps (/usr/share/atom/resources/app/node_modules/babel-core/node_modules/acorn-babel/acorn_csp.js:3053:16)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "language-ember-script",
      "atom-emblem",
      "es6-javascript"
    ],
    "themes": [
      "neutron-ui",
      "one-dark-syntax"
    ],
    "autoHideMenuBar": true
  }
}
```

### Installed Packages

```coffee
# User
aligner, v0.21.0
aligner-ruby, v1.4.0
autocomplete-ruby, v0.1.0
linter-jscs, v3.5.0
neutron-ui, v0.4.0
tree-view-git-status, v0.2.3

# Dev
No dev packages
```

**Comment by Arcanemagus** [comment] 2016-04-25 17:17
@NullVoxPopuli your Atom is _very very_ out of date, please update to the current version so it can understand the source code.

(It's so out of date it doesn't even check the required Atom version that would show it as being too old to run the package!)

**Comment by NullVoxPopuli** [comment] 2016-04-25 17:39
yup, I had this problem with other package, and re-downloaded atom. 

I thought atom auto-updated. Maybe it was too old to auto-update! lol. 

anyway, false alarm! love the linter-jscs. :-)
