### ISSUE TITLE
TypeError: Rule is not a function

### ISSUE THREAD

**Issue by stkrzysiak** [AtomLinter/linter-jscs#137] opened 2015-12-03 02:33 UTC
When creating a custom rule, I am constantly prompted that my rule is not a function.  JSCS via the CLI respects my additionalRules path in .jscsrc just fine, and validates my sample code properly, yet this doesn't seem to work within atom.  Is there something obvious I'm over-looking or should I dig in on this?  Maybe additionRules are not supported in the atom linter? Any input would be appreciated.
![jscs-rule-error](https://cloud.githubusercontent.com/assets/140278/11550283/dea5d452-9933-11e5-99c2-b585f947fb9c.png)

**Comment by Arcanemagus** [comment] 2015-12-03 04:20
We don't do any special handling of custom rules, in fact the only place I can think of as to where they might even be handled is from when we ask `jscs` to configure itself...

Are you using relative paths when attempting to set them? Can you try absolute paths and see if that fixes it?

**Comment by casesandberg** [comment] 2016-01-15 22:16
I just wrote a test for a custom rule and it seems to be working just fine. Can you paste your rule and .jscsrc file that you are having problem with?

**Comment by casesandberg** [comment] 2016-02-02 19:02
Marking as closed as I can not reproduce this. If you are still having issues please re-open.

**Closed by casesandberg** 2016-02-02 19:02 UTC
Labels: can't reproduce
