### ISSUE TITLE
When save a js file, unfold all lines

### ISSUE THREAD

**Issue by RiCoTeRoX** [AtomLinter/linter-jscs#189] opened 2016-02-18 20:00 UTC
Atom 1.5.2
linter-jscs 3.4.6

Fold all the file and save with some error to repair, then unfold all the lines.
It's pretty annoyed.

**Comment by casesandberg** [comment] 2016-02-18 20:06
Just tried this and it looks like it unfolds everything and then fixes it. Would the preferred behaviour be that it folds it back up again?

**Comment by RiCoTeRoX** [comment] 2016-02-18 20:28
yes, if i fold the code, don't want to unfold all.
Only fix it and nothing more.

:D

**Comment by Arcanemagus** [comment] 2016-02-18 20:32
Fixing that is actually a rather complex problem, this is actually a duplicate of #136.

**Closed by Arcanemagus** 2016-02-18 20:32 UTC
Labels: need more info
