### ISSUE TITLE
Assertion Error: plugin should be a function

### ISSUE THREAD

**Issue by pfefferle** [AtomLinter/linter-jscs#116] opened 2015-10-02 10:22 UTC
I got this error every time I open a JS-File (MacOS X 10.10.5, Atom 1.0.19, linter-jscs 3.0.0):

```
AssertionError: `plugin` should be a function
    at NodeConfiguration.Configuration._loadPlugin (/Users/pfefferle/.atom/packages/linter-jscs/node_modules/jscs/lib/config/configuration.js:503:5)
    at NodeConfiguration._loadPlugin (/Users/pfefferle/.atom/packages/linter-jscs/node_modules/jscs/lib/config/node-configuration.js:133:48)
    at NodeConfiguration.<anonymous> (/Users/pfefferle/.atom/packages/linter-jscs/node_modules/jscs/lib/config/configuration.js:433:18)
    at Array.forEach (native)
    at NodeConfiguration.Configuration._processConfig (/Users/pfefferle/.atom/packages/linter-jscs/node_modules/jscs/lib/config/configuration.js:432:25)
    at NodeConfiguration.Configuration.load (/Users/pfefferle/.atom/packages/linter-jscs/node_modules/jscs/lib/config/configuration.js:207:10)
    at [object Object].StringChecker.configure (/Users/pfefferle/.atom/packages/linter-jscs/node_modules/jscs/lib/string-checker.js:67:29)
    at [object Object].Checker.configure (/Users/pfefferle/.atom/packages/linter-jscs/node_modules/jscs/lib/checker.js:27:39)
    at Object.lint (/Users/pfefferle/.atom/packages/linter-jscs/index.js:102:19)
    at Promise.then._this.emitter.emit.linter (/Users/pfefferle/.atom/packages/linter/lib/linter-registry.coffee:59:22)
    at LinterRegistry.triggerLinter (/Users/pfefferle/.atom/packages/linter/lib/linter-registry.coffee:58:16)
    at /Users/pfefferle/.atom/packages/linter/lib/linter-registry.coffee:52:17
    at Array.map (native)
    at /Users/pfefferle/.atom/packages/linter/lib/linter-registry.coffee:50:27
```

**Comment by creynold** [comment] 2015-10-21 23:50
I get this error when running gulp-jscs

**Comment by kevinansfield** [comment] 2015-10-23 10:13
Same issue every time I open, type in or save a JS file.

```
AssertionError: `plugin` should be a function
    at NodeConfiguration.Configuration._loadPlugin (/Users/kevinansfield/.atom/packages/linter-jscs/node_modules/jscs/lib/config/configuration.js:554:5)
    at NodeConfiguration._loadPlugin (/Users/kevinansfield/.atom/packages/linter-jscs/node_modules/jscs/lib/config/node-configuration.js:134:48)
    at NodeConfiguration.<anonymous> (/Users/kevinansfield/.atom/packages/linter-jscs/node_modules/jscs/lib/config/configuration.js:480:18)
    at Array.forEach (native)
    at NodeConfiguration.Configuration._processConfig (/Users/kevinansfield/.atom/packages/linter-jscs/node_modules/jscs/lib/config/configuration.js:479:25)
    at NodeConfiguration.Configuration.load (/Users/kevinansfield/.atom/packages/linter-jscs/node_modules/jscs/lib/config/configuration.js:232:10)
    at [object Object].StringChecker.configure (/Users/kevinansfield/.atom/packages/linter-jscs/node_modules/jscs/lib/string-checker.js:67:29)
    at [object Object].Checker.configure (/Users/kevinansfield/.atom/packages/linter-jscs/node_modules/jscs/lib/checker.js:28:39)
    at Object.lint (/Users/kevinansfield/.atom/packages/linter-jscs/index.js:103:19)
    at Promise.then._this.emitter.emit.linter (/Users/kevinansfield/.atom/packages/linter/lib/linter-registry.coffee:59:22)
    at LinterRegistry.triggerLinter (/Users/kevinansfield/.atom/packages/linter/lib/linter-registry.coffee:58:16)
    at /Users/kevinansfield/.atom/packages/linter/lib/linter-registry.coffee:52:17
    at Array.map (native)
    at /Users/kevinansfield/.atom/packages/linter/lib/linter-registry.coffee:50:27
```

**Comment by Arcanemagus** [comment] 2015-10-23 16:17
From within the `linter-jscs` package folder (`~/.atom/packages/linter-jscs`) can you run `npm list --depth 0` and report which version of `jscs` is installed?

**Comment by pfefferle** [comment] 2015-10-23 20:56
* atom-linter@3.3.0
* atom-package-deps@2.1.3
* jscs@2.3.5

**Comment by Arcanemagus** [comment] 2015-10-23 20:59
Hmmm, I've got 2.2.1 installed, I wonder if something broke in the updates.

**Comment by Arcanemagus** [comment] 2015-10-23 21:11
I'm not seeing this issue with those dependency versions under Atom 1.0.19 and linter-jscs 3.1.2 on either Windows or Ubuntu. Could this maybe be an OS X specific bug?

**Comment by Arcanemagus** [comment] 2015-10-23 21:14
@pfefferle @kevinansfield I've only been testing with the "google" preset, are either of you using a customized set of options? If so try moving that file temporarily to test if that might be the issue?

**Comment by pfefferle** [comment] 2015-10-23 21:32
you are right, the problem is only when using a customized set of options (.jscsrc). it happens when I use plugins like the https://www.npmjs.com/package/jscs-jsdoc

```javascript
{
    "plugins": [
        "jscs-jsdoc"
    ],
    "jsDoc": {
        "checkAnnotations": "closurecompiler",
        "checkTypes": "strictNativeCase",
        "enforceExistence": "exceptExports"
    }
}
```

**Comment by Arcanemagus** [comment] 2015-10-23 22:01
Interesting, I wonder if the plugins can't be loaded via the programmatic interface directly? Did this work in the past?

**Comment by pezioz** [comment] 2015-11-02 08:39
I have the same problem. I am using the react plugin.

For information about the different versions I am using:
├── atom-linter@3.3.0
├── atom-package-deps@2.1.3
└── jscs@2.5.0

It was working in the past.

Do you have any idea where does it come from?

**Comment by kilianc** [comment] 2015-12-16 23:52
+ 1 on this

**Comment by casesandberg** [comment] 2016-01-17 20:51
Is this still an issue with the newest version of the `linter-jscs`?

**Comment by casesandberg** [comment] 2016-02-02 19:09
Marking as closed as I can not reproduce this. If you are still having issues please re-open.

**Closed by casesandberg** 2016-02-02 19:09 UTC
Labels: need more info

**Comment by amk221** [comment] 2016-02-09 16:21
Just started getting this too

linter-jscs@3.4.4 ~/Dropbox/dot/atom/packages/linter-jscs
├── atom-linter@4.4.0
├── atom-package-deps@3.0.7
├── globule@0.2.0
└── jscs@2.9.0

**Comment by Arcanemagus** [comment] 2016-02-09 18:02
What does your configuration file look like @amk221? This error is triggered from within the `jscs` code so it's _highly_ unlikely this is an issue with this package...

**Comment by amk221** [comment] 2016-02-09 19:21
Ah my bad, this was the only mention of the error I could find. You're right though, I removed "jscs-ember-deprecations" from "plugins" and it's ok now. Unfortunately not got time to investigate why.

**Comment by casesandberg** [comment] 2016-02-09 19:25
🙌

**Comment by Arcanemagus** [comment] 2016-02-09 19:51
Looks like you are referencing a plugin that you don't have installed :wink:.
