### ISSUE TITLE
Saving an .ejs file results in Uncaught TypeError

### ISSUE THREAD

**Issue by 9o** [AtomLinter/linter-jscs#82] opened 2015-07-30 04:39 UTC
1. Open an .ejs file
2. Save the file

**Atom Version**: 1.0.3
**System**: Mac OS X 10.11
**Thrown From**: [linter-jscs](https://github.com/AtomLinter/linter-jscs) package, v2.0.3

### Stack Trace

Uncaught TypeError: Cannot read property 'fixString' of undefined

```
At /Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:801

TypeError: Cannot read property 'fixString' of undefined
  at Function.fixString (/Users/henry/.atom/packages/linter-jscs/index.js:130:40)
  at /Users/henry/.atom/packages/linter-jscs/index.js:36:19
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at TextBuffer.module.exports.TextBuffer.saveAs (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:995:20)
  at TextBuffer.module.exports.TextBuffer.save (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:988:19)
  at TextEditor.module.exports.TextEditor.save (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:579:26)
  at Pane.module.exports.Pane.saveItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:539:18)
  at Pane.module.exports.Pane.saveActiveItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:522:19)
  at Workspace.module.exports.Workspace.saveActivePaneItem (/Applications/Atom.app/Contents/Resources/app.asar/src/workspace.js:609:35)
  at atom-workspace.atom.commands.add.core:save (/Applications/Atom.app/Contents/Resources/app.asar/src/workspace-element.js:293:30)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:241:29)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:524:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:347:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:177:20)

```

### Commands

```
     -1:14.2.0 tool-panel:unfocus (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -1:08.2.0 core:save (atom-text-editor.editor.is-focused)
     -1:01.1.0 settings-view:check-for-package-updates (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-dark-syntax.theme-one-dark-ui)
     -0:25.7.0 core:cancel (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-dark-syntax.theme-one-dark-ui)
     -0:01.5.0 core:save (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "ignoredNames": [
      ".git",
      ".svn",
      ".DS_Store"
    ],
    "disabledPackages": [
      "atom-jsfmt",
      "autohide-tree-view"
    ]
  },
  "linter-jscs": {
    "esnext": true,
    "fixOnSave": true
  }
}
```

### Installed Packages

```coffee
# User
auto-indent, v0.5.0
color-picker, v2.0.11
emmet, v2.3.12
inline-autocomplete, v1.1.0
jshint, v1.3.10
language-css, v0.32.1
language-ejs, v0.2.0
linter, v1.2.4
linter-htmlhint, v0.0.17
linter-jscs, v2.0.3
minimap, v4.12.1
open-recent, v2.3.0
pulsing-cursor, v0.3.1
react, v0.12.6
sass-autocompile, v0.7.3
webbox-color, v0.5.8

# Dev
No dev packages
```

**Comment by Arcanemagus** [comment] 2015-10-29 23:43
Marking as a duplicate of #84 as they are the same issue and more discussion has happened on that issue.

**Closed by Arcanemagus** 2015-10-29 23:43 UTC
