### ISSUE TITLE
Uncaught Error: Parse error on line 14:...ress": "^4.14.0",  }}----------------------^Expectin...

### ISSUE THREAD

**Issue by devjanaprime** [AtomLinter/linter-jscs#276] opened 2016-06-29 01:58 UTC
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.8.0
**System**: Mac OS X 10.11.4
**Thrown From**: [linter-jscs](https://github.com/AtomLinter/linter-jscs) package, v4.0.4

### Stack Trace

Uncaught Error: Parse error on line 14:
...ress": "^4.14.0",  }}
----------------------^
Expecting 'STRING', got '}'

```
At /Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:1002

Error: Parse error on line 14:
...ress": "^4.14.0",  }}
----------------------^
Expecting 'STRING', got '}'
    at Object.parseError (/Users/devjana/.atom/packages/linter-jscs/node_modules/jscs/node_modules/jsonlint/lib/jsonlint.js:55:11)
    at Object.parse (/Users/devjana/.atom/packages/linter-jscs/node_modules/jscs/node_modules/jsonlint/lib/jsonlint.js:132:22)
    at exports.parse (/Users/devjana/.atom/packages/linter-jscs/node_modules/jscs/node_modules/jsonlint/lib/jsonlint.js:417:53)
    at Object.exports.getContent (/Users/devjana/.atom/packages/linter-jscs/node_modules/jscs/lib/cli-config.js:81:27)
    at Object.<anonymous> (/Users/devjana/.atom/packages/linter-jscs/node_modules/jscs/lib/cli-config.js:142:31)
    at /Users/devjana/.atom/packages/linter-jscs/node_modules/jscs/lib/cli-config.js:36:24
    at Array.filter (native)
    at findup (/Users/devjana/.atom/packages/linter-jscs/node_modules/jscs/lib/cli-config.js:32:25)
    at Object.exports.load (/Users/devjana/.atom/packages/linter-jscs/node_modules/jscs/lib/cli-config.js:140:9)
    at Function.getConfig (/Users/devjana/.atom/packages/linter-jscs/src/linter-jscs.js:201:27)
    at /Users/devjana/.atom/packages/linter-jscs/src/linter-jscs.js:89:31
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at TextBuffer.module.exports.TextBuffer.saveAs (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1091:20)
    at TextBuffer.module.exports.TextBuffer.save (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1083:19)
    at TextEditor.module.exports.TextEditor.save (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:660:26)
    at Pane.module.exports.Pane.saveItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:718:18)
    at Pane.module.exports.Pane.saveActiveItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:701:19)
    at Workspace.module.exports.Workspace.saveActivePaneItem (/Applications/Atom.app/Contents/Resources/app.asar/src/workspace.js:684:35)
    at atom-workspace.commandRegistry.add.core:save (/Applications/Atom.app/Contents/Resources/app.asar/src/register-default-commands.js:214:32)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:580:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:388:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:98:36)
    at HTMLDocument.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:3:61)
```

### Commands

```
     -5:52.1.0 core:backspace (atom-text-editor.editor.is-focused)
     -5:51.9.0 core:move-down (atom-text-editor.editor.is-focused)
  2x -5:51.8.0 core:backspace (atom-text-editor.editor.is-focused)
 25x -5:46.4.0 core:move-right (atom-text-editor.editor.is-focused)
  3x -5:37 core:move-down (atom-text-editor.editor.is-focused)
     -5:25.6.0 core:copy (atom-text-editor.editor.is-focused)
     -5:00.1.0 core:backspace (atom-text-editor.editor.is-focused)
     -4:54.9.0 tree-view:remove (span.name.icon.icon-file-directory)
     -4:50.9.0 core:backspace (atom-text-editor.editor.is-focused)
     -4:47.3.0 tree-view:remove (span.name.icon.icon-file-directory)
     -2:38.5.0 core:save (atom-text-editor.editor.is-focused)
     -2:22.3.0 core:copy (atom-text-editor.editor.is-focused)
     -2:19.4.0 core:paste (atom-text-editor.editor.is-focused.autocomplete-active)
  4x -2:18.5.0 core:save (atom-text-editor.editor.is-focused)
     -1:35.9.0 settings-view:check-for-package-updates (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-dark-syntax.theme-one-dark-ui)
  2x -0:16.5.0 core:save (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "linter",
      "linter-jscs"
    ]
  }
}
```

### Installed Packages

```coffee
# User
autoclose-html, v0.23.0
linter-csslint, v1.3.2
linter-htmlhint, v1.2.1
linter-jshint, v2.1.0
minimap, v4.24.6
minimap-highlight-selected, v4.4.0
open-recent, v5.0.0
pigments, v0.29.3
rest-client, v1.1.1
terminal-plus, v0.14.5

# Dev
No dev packages
```

**Comment by Arcanemagus** [comment] 2016-06-29 02:23
Duplicate of https://github.com/AtomLinter/linter-jscs/issues/257.

Looks like you have a trailing comma in your `.jscsrc` or `package.json` file.

**Closed by Arcanemagus** 2016-06-29 02:23 UTC
Labels: duplicate
