### ISSUE TITLE
Unable to save file once the following error is thrown (Uncaught AssertionError: Preset "ember-suave" does not exist)

### ISSUE THREAD

**Issue by kvickyk** [AtomLinter/linter-jscs#333] opened 2017-03-23 19:52 UTC
Steps:

1. Open any file where there is a call to the parent method as someFunction.apply(this, arguments)
2. change it to someFunction(...arguments)

The error shows up and will not allow me to save the file. If I disable the plugin and then save the file, enable the plugin again, there is no error.

It is very annoying when the error does not allow you to save the file and the only way around it is to disable the plugin and save it.

I feel that no matter what errors are thrown, it should not block the user from saving the file.

**Atom**: 1.15.0 x64
**Electron**: 1.3.13
**OS**: Mac OS X 10.12.3
**Thrown From**: [linter-jscs](https://github.com/AtomLinter/linter-jscs) package 4.1.2

### Stack Trace

Uncaught AssertionError: Preset "ember-suave" does not exist

```
At /Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:1045

AssertionError: Preset "ember-suave" does not exist
    at NodeConfiguration.Configuration._loadPreset (/packages/linter-jscs/node_modules/jscs/lib/config/configuration.js:692:5)
    at NodeConfiguration._loadPreset (/packages/linter-jscs/node_modules/jscs/lib/config/node-configuration.js:160:41)
    at NodeConfiguration.Configuration._processConfig (/packages/linter-jscs/node_modules/jscs/lib/config/configuration.js:529:14)
    at NodeConfiguration.Configuration.load (/packages/linter-jscs/node_modules/jscs/lib/config/configuration.js:211:10)
    at Checker.configure (/packages/linter-jscs/node_modules/jscs/lib/string-checker.js:62:29)
    at Checker.configure (/packages/linter-jscs/node_modules/jscs/lib/checker.js:27:39)
    at fixString (/packages/linter-jscs/src/linter-jscs.js:87:8)
    at /packages/linter-jscs/src/linter-jscs.js:191:13
    at Function.module.exports.Emitter.simpleDispatch (/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/app.asar/node_modules/event-kit/lib/emitter.js:129:28)
    at TextBuffer.module.exports.TextBuffer.saveAs (/app.asar/node_modules/text-buffer/lib/text-buffer.js:1059:20)
    at TextBuffer.module.exports.TextBuffer.save (/app.asar/node_modules/text-buffer/lib/text-buffer.js:1048:19)
    at TextEditor.module.exports.TextEditor.save (/app.asar/src/text-editor.js:915:26)
    at Pane.module.exports.Pane.saveItem (/app.asar/src/pane.js:753:18)
    at Pane.saveItem (/app.asar/src/pane.js:3:59)
    at Pane.module.exports.Pane.saveActiveItem (/app.asar/src/pane.js:736:19)
    at Workspace.module.exports.Workspace.saveActivePaneItem (/app.asar/src/workspace.js:693:35)
    at /app.asar/src/register-default-commands.js:225:32)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/app.asar/src/command-registry.js:259:29)
    at /app.asar/src/command-registry.js:3:59
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:599:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:390:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/app.asar/src/window-event-handler.js:106:36)
    at /app.asar/src/window-event-handler.js:3:59)
```

### Commands

```
  2x -1:14.5.0 core:save (input.hidden-input)
     -0:45.1.0 tabs:close-other-tabs (li.tab.sortable.active.right-clicked)
     -0:38.8.0 fuzzy-finder:toggle-file-finder (div.panels)
     -0:33.5.0 core:confirm (input.hidden-input)
     -0:19.3.0 vim-mode-plus:move-to-previous-word (input.hidden-input)
     -0:18.8.0 vim-mode-plus:delete (input.hidden-input)
     -0:18.8.0 vim-mode-plus:move-to-next-word (input.hidden-input)
     -0:18.5.0 vim-mode-plus:move-left (input.hidden-input)
     -0:18.3.0 vim-mode-plus:delete-right (input.hidden-input)
     -0:17.8.0 vim-mode-plus:move-right (input.hidden-input)
     -0:17.6.0 vim-mode-plus:delete (input.hidden-input)
     -0:17.5.0 vim-mode-plus:move-to-next-word (input.hidden-input)
  2x -0:17.1.0 vim-mode-plus:delete-right (input.hidden-input)
     -0:16.8.0 vim-mode-plus:activate-insert-mode (input.hidden-input)
     -0:16.1.0 vim-mode-plus:activate-normal-mode (input.hidden-input)
     -0:15.5.0 core:save (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.29.17 
busy-signal 1.3.0 
change-case 0.6.3 
intentions 1.1.2 
language-gradle 0.0.3 
linter 2.1.2 
linter-jscs 4.1.2 
linter-jshint 3.0.3 
linter-ui-default 1.2.1 
vim-mode-plus 0.84.1 
```

**Comment by Arcanemagus** [comment] 2017-03-23 21:49
Duplicate of #332 (and probably others). JSCS development is dead so I am putting no major effort into supporting this. If you want to take the time to figure out what is wrong and submit a PR I'd be happy to review it 😉.

If you don't want this to cause issues, just disable the fixOnSave functionality as it is some broken aspect of that that causes this.

**Closed by Arcanemagus** 2017-03-23 21:49 UTC
