### ISSUE TITLE
Uncaught Error: Parse error on line 61:...{    "database": {<<<<<<< HEAD      "----------------...

### ISSUE THREAD

**Issue by flacnut** [AtomLinter/linter-jscs#258] opened 2016-05-27 23:13 UTC
Opening a file while doing a git-merge, even after making the file valid, I cannot save the fixed changes, i continue to get this error.

**Atom Version**: 1.7.4
**System**: Mac OS X 10.10.5
**Thrown From**: [linter-jscs](https://github.com/AtomLinter/linter-jscs) package, v4.0.2

### Stack Trace

Uncaught Error: Parse error on line 61:
...{    "database": {<<<<<<< HEAD      "
---------------------^
Expecting 'STRING', '}', got 'undefined'

```
At /Users/flacnut/dev/Setup/Atom.app/Contents/Resources/app.asar/src/pane.js:1002

Error: Parse error on line 61:
...{    "database": {<<<<<<< HEAD      "
---------------------^
Expecting 'STRING', '}', got 'undefined'
    at Object.parseError (/Users/flacnut/.atom/packages/linter-jscs/node_modules/jscs/node_modules/jsonlint/lib/jsonlint.js:55:11)
    at Object.parse (/Users/flacnut/.atom/packages/linter-jscs/node_modules/jscs/node_modules/jsonlint/lib/jsonlint.js:132:22)
    at exports.parse (/Users/flacnut/.atom/packages/linter-jscs/node_modules/jscs/node_modules/jsonlint/lib/jsonlint.js:417:53)
    at Object.exports.getContent (/Users/flacnut/.atom/packages/linter-jscs/node_modules/jscs/lib/cli-config.js:81:27)
    at Object.<anonymous> (/Users/flacnut/.atom/packages/linter-jscs/node_modules/jscs/lib/cli-config.js:142:31)
    at /Users/flacnut/.atom/packages/linter-jscs/node_modules/jscs/lib/cli-config.js:36:24
    at Array.filter (native)
    at findup (/Users/flacnut/.atom/packages/linter-jscs/node_modules/jscs/lib/cli-config.js:32:25)
    at Object.exports.load (/Users/flacnut/.atom/packages/linter-jscs/node_modules/jscs/lib/cli-config.js:140:9)
    at Function.getConfig (/Users/flacnut/.atom/packages/linter-jscs/src/linter-jscs.js:237:27)
    at /Users/flacnut/.atom/packages/linter-jscs/src/linter-jscs.js:104:31
    at Function.module.exports.Emitter.simpleDispatch (/Users/flacnut/dev/Setup/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Users/flacnut/dev/Setup/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at TextBuffer.module.exports.TextBuffer.saveAs (/Users/flacnut/dev/Setup/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1091:20)
    at TextBuffer.module.exports.TextBuffer.save (/Users/flacnut/dev/Setup/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1083:19)
    at TextEditor.module.exports.TextEditor.save (/Users/flacnut/dev/Setup/Atom.app/Contents/Resources/app.asar/src/text-editor.js:660:26)
    at Pane.module.exports.Pane.saveItem (/Users/flacnut/dev/Setup/Atom.app/Contents/Resources/app.asar/src/pane.js:718:18)
    at Pane.module.exports.Pane.saveActiveItem (/Users/flacnut/dev/Setup/Atom.app/Contents/Resources/app.asar/src/pane.js:701:19)
    at Workspace.module.exports.Workspace.saveActivePaneItem (/Users/flacnut/dev/Setup/Atom.app/Contents/Resources/app.asar/src/workspace.js:684:35)
    at atom-workspace.commandRegistry.add.core:save (/Users/flacnut/dev/Setup/Atom.app/Contents/Resources/app.asar/src/register-default-commands.js:214:32)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Users/flacnut/dev/Setup/Atom.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
    at /Users/flacnut/dev/Setup/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Users/flacnut/dev/Setup/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:580:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Users/flacnut/dev/Setup/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:388:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/Users/flacnut/dev/Setup/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:98:36)
    at HTMLDocument.<anonymous> (/Users/flacnut/dev/Setup/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:3:61)
```

### Commands

```
     -0:01.6.0 core:select-all (atom-text-editor.editor.is-focused)
     -0:01.3.0 core:paste (atom-text-editor.editor.is-focused)
     -0:00.6.0 core:save (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "jshint",
      "emmet",
      "atom-ternjs",
      "markdown-preview"
    ],
    "ignoredNames": [
      ".git",
      ".DS_Store"
    ],
    "packagesWithKeymapsDisabled": [],
    "projectHome": "/Users/flacnut/dev",
    "themes": [
      "one-dark-ui",
      "atom-dark-syntax"
    ]
  },
  "linter-jscs": {
    "configPath": "./.eslintrc",
    "onlyConfig": true,
    "preset": "google"
  }
}
```

### Installed Packages

```coffee
# User
atom-typescript, v8.10.2
autocomplete-go, v1.1.0
builder-go, v1.0.0
file-icons, v1.7.12
go-config, v1.1.4
go-get, v1.0.3
go-plus, v4.1.0
gofmt, v1.1.6
gometalinter-linter, v1.1.0
gorename, v1.0.2
indent-guide-improved, v1.4.8
linter, v1.11.4
linter-js-yaml, v1.2.5
linter-jscs, v4.0.2
markdown-preview-plus, v2.4.0
markdown-preview-plus-opener, v0.2.0
minimap, v4.24.3
minimap-find-and-replace, v4.5.1
minimap-git-diff, v4.3.1
minimap-selection, v4.4.0
navigator-godef, v1.0.3
tester-go, v1.0.4

# Dev
No dev packages
```

**Comment by Arcanemagus** [comment] 2016-05-27 23:21
Duplicate of #257.

**Closed by Arcanemagus** 2016-05-27 23:21 UTC
