### ISSUE TITLE
Uncaught Error: Parse error on line 32:...-logger": "^2.0.1",<<<<<<< HEAD    "sl---------------...

### ISSUE THREAD

**Issue by mapy69003** [AtomLinter/linter-jscs#270] opened 2016-06-17 15:12 UTC
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.8.0
**System**: "Manjaro Linux"
**Thrown From**: [linter-jscs](https://github.com/AtomLinter/linter-jscs) package, v4.0.3

### Stack Trace

Uncaught Error: Parse error on line 32:
...-logger": "^2.0.1",<<<<<<< HEAD    "sl
----------------------^
Expecting 'STRING', got 'undefined'

```
At /usr/share/atom/resources/app.asar/src/pane.js:1002

Error: Parse error on line 32:
...-logger": "^2.0.1",<<<<<<< HEAD    "sl
----------------------^
Expecting 'STRING', got 'undefined'
    at Object.parseError (/home/yoannp/.atom/packages/linter-jscs/node_modules/jscs/node_modules/jsonlint/lib/jsonlint.js:55:11)
    at Object.parse (/home/yoannp/.atom/packages/linter-jscs/node_modules/jscs/node_modules/jsonlint/lib/jsonlint.js:132:22)
    at exports.parse (/home/yoannp/.atom/packages/linter-jscs/node_modules/jscs/node_modules/jsonlint/lib/jsonlint.js:417:53)
    at Object.exports.getContent (/home/yoannp/.atom/packages/linter-jscs/node_modules/jscs/lib/cli-config.js:81:27)
    at Object.<anonymous> (/home/yoannp/.atom/packages/linter-jscs/node_modules/jscs/lib/cli-config.js:142:31)
    at /home/yoannp/.atom/packages/linter-jscs/node_modules/jscs/lib/cli-config.js:36:24
    at Array.filter (native)
    at findup (/home/yoannp/.atom/packages/linter-jscs/node_modules/jscs/lib/cli-config.js:32:25)
    at Object.exports.load (/home/yoannp/.atom/packages/linter-jscs/node_modules/jscs/lib/cli-config.js:140:9)
    at Function.getConfig (/home/yoannp/.atom/packages/linter-jscs/src/linter-jscs.js:237:27)
    at /home/yoannp/.atom/packages/linter-jscs/src/linter-jscs.js:104:31
    at Function.module.exports.Emitter.simpleDispatch (/usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at TextBuffer.module.exports.TextBuffer.saveAs (/usr/share/atom/resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1091:20)
    at TextBuffer.module.exports.TextBuffer.save (/usr/share/atom/resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1083:19)
    at TextEditor.module.exports.TextEditor.save (/usr/share/atom/resources/app.asar/src/text-editor.js:660:26)
    at Pane.module.exports.Pane.saveItem (/usr/share/atom/resources/app.asar/src/pane.js:718:18)
    at Pane.module.exports.Pane.saveActiveItem (/usr/share/atom/resources/app.asar/src/pane.js:701:19)
    at Workspace.module.exports.Workspace.saveActivePaneItem (/usr/share/atom/resources/app.asar/src/workspace.js:684:35)
    at atom-workspace.commandRegistry.add.core:save (/usr/share/atom/resources/app.asar/src/register-default-commands.js:214:32)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app.asar/src/command-registry.js:260:29)
    at /usr/share/atom/resources/app.asar/src/command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/usr/share/atom/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:580:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/usr/share/atom/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:388:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/usr/share/atom/resources/app.asar/src/window-event-handler.js:98:36)
    at HTMLDocument.<anonymous> (/usr/share/atom/resources/app.asar/src/window-event-handler.js:3:61)
```

### Commands

```
     -0:39.3.0 core:copy (atom-text-editor.editor.is-focused)
     -0:39.1.0 editor:move-to-end-of-screen-line (atom-text-editor.editor.is-focused)
     -0:38.7.0 editor:newline (atom-text-editor.editor.is-focused)
     -0:38.5.0 core:paste (atom-text-editor.editor.is-focused)
     -0:34.5.0 core:save (atom-text-editor.editor.is-focused.autocomplete-active)
  3x -0:28.1.0 core:copy (atom-text-editor.editor.is-focused)
     -0:25.3.0 core:paste (atom-text-editor.editor.is-focused)
  3x -0:24.8.0 core:save (atom-text-editor.editor.is-focused)
  2x -0:17.4.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:16.4.0 core:save (atom-text-editor.editor.is-focused)
     -0:14.6.0 core:cut (atom-text-editor.editor.is-focused)
     -0:14 core:save (atom-text-editor.editor.is-focused)
  3x -0:12.1.0 core:cut (atom-text-editor.editor.is-focused)
     -0:10.5.0 core:save (atom-text-editor.editor.is-focused)
     -0:08.7.0 core:cut (atom-text-editor.editor.is-focused)
  2x -0:08.3.0 core:save (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "autoHideMenuBar": true,
    "disabledPackages": [
      "wrap-guide",
      "activate-power-mode",
      "jshint"
    ],
    "themes": [
      "seti-ui",
      "one-dark-syntax"
    ]
  },
  "linter-jscs": {
    "fixOnSave": true
  }
}
```

### Installed Packages

```coffee
# User
atom-beautify, v0.29.8
git-control, v0.7.1
linter, v1.11.11
linter-gcc, v0.6.14
linter-jscs, v4.0.3
linter-jshint, v2.1.0
minimap, v4.24.6
php-cs-fixer, v2.5.6
seti-ui, v1.3.1
tabs-to-spaces, v1.0.2

# Dev
No dev packages
```

**Comment by Arcanemagus** [comment] 2016-06-17 16:30
Marking as a duplicate of #257.

Looks like either your `package.json` or `.jscsrc` file is in the process of a merge conflict right now.

**Closed by Arcanemagus** 2016-06-17 16:30 UTC
