### ISSUE TITLE
Uncaught AssertionError: Unable to add an error, `column` should be a positive number but -208 given

### ISSUE THREAD

**Issue by skarfacegc** [AtomLinter/linter-jscs#193] opened 2016-02-21 02:57 UTC
[Enter steps to reproduce below:]

saved my file which kicked off a jscs run (and possibly a jshint run)
code

```js
var config = {
  unit_tests: {
    test_files = ['test/unit/**/*.js'],
    watch_files = [].concat([config.unit_tests.test_files, 'lib/**/*.js']);
  },
  api_tests: {
    test_files = ['test/api/**/*.js'],
    watch_files = [].concat([config.api_tests.test_files], 'lib/WebService/**/*.js');
  }
};
```

**Atom Version**: 1.5.3
**System**: Mac OS X 10.10.5
**Thrown From**: [linter-jscs](https://github.com/AtomLinter/linter-jscs) package, v3.4.6

### Stack Trace

Uncaught AssertionError: Unable to add an error, `column` should be a positive number but -208 given

```
At /opt/homebrew-cask/Caskroom/atom/1.5.3/Atom.app/Contents/Resources/app.asar/src/pane.js:825

AssertionError: Unable to add an error, `column` should be a positive number but -208 given
    at Object.Errors._validateInput (/Users/andrew/.atom/packages/linter-jscs/node_modules/jscs/lib/errors.js:73:9)
    at Object.Errors.add (/Users/andrew/.atom/packages/linter-jscs/node_modules/jscs/lib/errors.js:46:14)
    at [object Object].StringChecker._addParseError (/Users/andrew/.atom/packages/linter-jscs/node_modules/jscs/lib/string-checker.js:211:16)
    at [object Object].<anonymous> (/Users/andrew/.atom/packages/linter-jscs/node_modules/jscs/lib/string-checker.js:253:22)
    at Array.forEach (native)
    at [object Object].StringChecker.fixString (/Users/andrew/.atom/packages/linter-jscs/node_modules/jscs/lib/string-checker.js:252:25)
    at Function.fixString (/Users/andrew/.atom/packages/linter-jscs/src/linter-jscs.js:212:33)
    at /Users/andrew/.atom/packages/linter-jscs/src/linter-jscs.js:88:18
    at Function.module.exports.Emitter.simpleDispatch (/opt/homebrew-cask/Caskroom/atom/1.5.3/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/opt/homebrew-cask/Caskroom/atom/1.5.3/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at TextBuffer.module.exports.TextBuffer.saveAs (/opt/homebrew-cask/Caskroom/atom/1.5.3/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1067:27)
    at TextBuffer.module.exports.TextBuffer.save (/opt/homebrew-cask/Caskroom/atom/1.5.3/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1037:19)
    at TextEditor.module.exports.TextEditor.save (/opt/homebrew-cask/Caskroom/atom/1.5.3/Atom.app/Contents/Resources/app.asar/src/text-editor.js:630:26)
    at Pane.module.exports.Pane.saveItem (/opt/homebrew-cask/Caskroom/atom/1.5.3/Atom.app/Contents/Resources/app.asar/src/pane.js:545:18)
    at Pane.module.exports.Pane.saveActiveItem (/opt/homebrew-cask/Caskroom/atom/1.5.3/Atom.app/Contents/Resources/app.asar/src/pane.js:528:19)
    at Workspace.module.exports.Workspace.saveActivePaneItem (/opt/homebrew-cask/Caskroom/atom/1.5.3/Atom.app/Contents/Resources/app.asar/src/workspace.js:649:35)
    at atom-workspace.commandRegistry.add.core:save (/opt/homebrew-cask/Caskroom/atom/1.5.3/Atom.app/Contents/Resources/app.asar/src/register-default-commands.js:173:32)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/opt/homebrew-cask/Caskroom/atom/1.5.3/Atom.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
    at /opt/homebrew-cask/Caskroom/atom/1.5.3/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/opt/homebrew-cask/Caskroom/atom/1.5.3/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:536:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/opt/homebrew-cask/Caskroom/atom/1.5.3/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:359:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeydown (/opt/homebrew-cask/Caskroom/atom/1.5.3/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:97:36)
    at HTMLDocument.<anonymous> (/opt/homebrew-cask/Caskroom/atom/1.5.3/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:3:61)
```

### Commands

```
  3x -1:10.8.0 core:move-up (atom-text-editor.editor.is-focused)
  3x -1:10.1.0 core:select-down (atom-text-editor.editor.is-focused)
     -1:08.6.0 core:backspace (atom-text-editor.editor.is-focused)
     -1:02.4.0 editor:newline (atom-text-editor.editor.is-focused)
  9x -0:58.6.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:47.5.0 editor:move-to-end-of-line (atom-text-editor.editor.is-focused)
     -0:46.1.0 editor:newline (atom-text-editor.editor.is-focused)
     -0:38.1.0 core:backspace (atom-text-editor.editor.is-focused.autocomplete-active)
     -0:28.3.0 core:move-down (atom-text-editor.editor.is-focused.autocomplete-active)
     -0:27.8.0 autocomplete-plus:confirm (atom-text-editor.editor.is-focused.autocomplete-active)
     -0:26.3.0 core:move-right (atom-text-editor.editor.is-focused)
  3x -0:10.9.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:06.3.0 editor:move-to-end-of-line (atom-text-editor.editor.is-focused)
     -0:04.5.0 editor:newline (atom-text-editor.editor.is-focused)
  3x -0:04.1.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:03.0 core:save (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "projectHome": "/Users/andrew/Development",
    "themes": [
      "one-dark-ui",
      "solarized-dark-syntax"
    ]
  },
  "linter-jscs": {
    "fixOnSave": true,
    "preset": "google"
  }
}
```

### Installed Packages

```coffee
# User
atom-beautify, v0.28.22
autocomplete-paths, v1.0.2
fonts, v1.1.0
git-plus, v5.13.0
highlight-selected, v0.11.2
imdone-atom, v1.3.25
imdone-atom-github, v0.1.9
lcov-info, v0.11.0
linter, v1.11.3
linter-jscs, v3.4.6
linter-jshint, v1.3.1
minimap, v4.19.0
mocha-test-runner, v0.4.7
remote-edit, v1.8.24
sync-settings, v0.6.0
terminal-plus, v0.14.5

# Dev
No dev packages
```

**Comment by xyber3364** [comment] 2016-02-21 22:29
:+1: 
This happens when in a JavaScript file you make an object using the equals instead of the colon.

Example
`var obj={a=1,b=2};`
instead of
`var obj={a:1,b=2};`

**Comment by skarfacegc** [comment] 2016-02-22 15:53
I know what caused it, should still probably be handled.

**Comment by jgrodskiy-donlen** [comment] 2016-02-22 18:56
I agree, I am not a developer for this project just wanted to bump up this issue.

**Comment by Arcanemagus** [comment] 2016-02-23 06:19
Looks like this is an issue with `jscs` itself:
![image](https://cloud.githubusercontent.com/assets/427137/13243277/28b5ca7a-d9b2-11e5-9ab0-bc520e06c832.png)

Can you file an issue over there referencing this one? Marking this as closed as the problem isn't in this project and there is nothing that can be done about it here.

**Closed by Arcanemagus** 2016-02-23 06:19 UTC

**Comment by Arcanemagus** [comment] 2016-02-23 06:31
I already had most of the info up, so I just went ahead and filed it, feel free to subscribe there for updates on when it is fixed!

**Comment by skarfacegc** [comment] 2016-02-23 16:32
@Arcanemagus thanks!

**Comment by Arcanemagus** [comment] 2016-05-20 05:43
Looks like this bug won't be fixed at the source, the referenced issue was just closed as orphaned.
