### ISSUE TITLE
Files specified in excludeFiles from .jscsrc are being linted anyway

### ISSUE THREAD

**Issue by adambuczynski** [AtomLinter/linter-jscs#83] opened 2015-07-30 06:47 UTC
I have the following .jscsrc file in my project root:

```json
{
  "preset": "google",
  "fileExtensions": [".js"],
  "maxErrors": 100,
  "verbose": false,
  "excludeFiles": [
    "public/**",
    "node_modules/**",
    "client/vendor/**",
    "client/static/**"
  ]
}
```

Yet when I open a file from the client/vendor folder, it starts to apply jscs rules and shows warnings:

![ss](https://www.dropbox.com/s/6e4gtzg7qeitch8/Screenshot%202015-07-30%2018.45.56.png?dl=1)

Am I doing something wrong? I've followed the instructions for the `excludeFiles` option as per http://jscs.info/overview.html#options so I assume the syntax is correct. It works correctly for gulp-jscs.

**Comment by acusti** [comment] 2015-08-25 18:00
I expect this has to do with your `.jscsrc` config file never getting loaded (related: #85, #96, #93).

**Comment by janaagaard75** [comment] 2015-12-22 12:29
I have the same issue.

I'm sure `.jscsrc` is being loading, because if I change some of the rules, the error reported by JSCS inside Atom match the updated rules. I have tried settings `excludeFiles` to something really simple like `["*.js"]`, `["**"]` or `["**/*.js"]`, but JSCS is still validating the files.

My `package.json` and `.jscsrc` are both located in the root folder. Renaming `package.json` to something else does not fix the issue.

Moving the settings into `jscsConfig` in `packages.json` gives the same result as with the `.jscsrc` file: The settings are read from `packages.json`, but `excludeFiles` is being ignored.

Renaming `excludedFiles` to something random, gives a warning in Atom about the settings not being understood.

**Comment by Arcanemagus** [comment] 2015-12-22 17:33
This looks like a bug with `jscs`, it's properly configuring itself as you deduced, and we are [passing the filePath](https://github.com/AtomLinter/linter-jscs/blob/v3.2.0/index.js#L121) to the `checkString` call, so it _should_ be working.

I'll file an issue over there to see whether this is working as intended or not.

**Comment by Arcanemagus** [comment] 2015-12-23 17:12
Looks like `jscs` doesn't want to support their ignore patterns when checking a string, even though other linters that support specifying a file path for stdin input do... so a workaround would need to be written for this project to support those. A PR implementing this would be welcome :wink:.

**Comment by casesandberg** [comment] 2016-01-13 23:02
This has been fixed and merged in!

**Closed by casesandberg** 2016-01-13 23:02 UTC

**Comment by adambuczynski** [comment] 2016-01-13 23:15
Thanks!
