### ISSUE TITLE
Uncaught Error: Parse error on line 1:^Expecting 'STRING', 'NUMBER', 'NULL', 'TRUE', 'FALSE', ...

### ISSUE THREAD

**Issue by Jguardado** [AtomLinter/linter-jscs#265] opened 2016-06-08 23:25 UTC
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.8.0
**System**: Mac OS X 10.11.5
**Thrown From**: [linter-jscs](https://github.com/AtomLinter/linter-jscs) package, v4.0.3

### Stack Trace

Uncaught Error: Parse error on line 1:

^
Expecting 'STRING', 'NUMBER', 'NULL', 'TRUE', 'FALSE', '{', '[', got 'EOF'

```
At /Users/JuansMacbook/Downloads/Atom.app/Contents/Resources/app.asar/src/pane.js:1002

Error: Parse error on line 1:

^
Expecting 'STRING', 'NUMBER', 'NULL', 'TRUE', 'FALSE', '{', '[', got 'EOF'
    at Object.parseError (/Users/JuansMacbook/.atom/packages/linter-jscs/node_modules/jscs/node_modules/jsonlint/lib/jsonlint.js:55:11)
    at Object.parse (/Users/JuansMacbook/.atom/packages/linter-jscs/node_modules/jscs/node_modules/jsonlint/lib/jsonlint.js:132:22)
    at exports.parse (/Users/JuansMacbook/.atom/packages/linter-jscs/node_modules/jscs/node_modules/jsonlint/lib/jsonlint.js:417:53)
    at Object.exports.getContent (/Users/JuansMacbook/.atom/packages/linter-jscs/node_modules/jscs/lib/cli-config.js:81:27)
    at Object.<anonymous> (/Users/JuansMacbook/.atom/packages/linter-jscs/node_modules/jscs/lib/cli-config.js:142:31)
    at /Users/JuansMacbook/.atom/packages/linter-jscs/node_modules/jscs/lib/cli-config.js:36:24
    at Array.filter (native)
    at findup (/Users/JuansMacbook/.atom/packages/linter-jscs/node_modules/jscs/lib/cli-config.js:32:25)
    at Object.exports.load (/Users/JuansMacbook/.atom/packages/linter-jscs/node_modules/jscs/lib/cli-config.js:140:9)
    at Function.getConfig (/Users/JuansMacbook/.atom/packages/linter-jscs/src/linter-jscs.js:214:27)
    at /Users/JuansMacbook/.atom/packages/linter-jscs/src/linter-jscs.js:89:31
    at Function.module.exports.Emitter.simpleDispatch (/Users/JuansMacbook/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Users/JuansMacbook/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at TextBuffer.module.exports.TextBuffer.saveAs (/Users/JuansMacbook/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1091:20)
    at TextBuffer.module.exports.TextBuffer.save (/Users/JuansMacbook/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1083:19)
    at TextEditor.module.exports.TextEditor.save (/Users/JuansMacbook/Downloads/Atom.app/Contents/Resources/app.asar/src/text-editor.js:660:26)
    at Pane.module.exports.Pane.saveItem (/Users/JuansMacbook/Downloads/Atom.app/Contents/Resources/app.asar/src/pane.js:718:18)
    at Pane.module.exports.Pane.saveActiveItem (/Users/JuansMacbook/Downloads/Atom.app/Contents/Resources/app.asar/src/pane.js:701:19)
    at Workspace.module.exports.Workspace.saveActivePaneItem (/Users/JuansMacbook/Downloads/Atom.app/Contents/Resources/app.asar/src/workspace.js:684:35)
    at atom-workspace.commandRegistry.add.core:save (/Users/JuansMacbook/Downloads/Atom.app/Contents/Resources/app.asar/src/register-default-commands.js:214:32)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Users/JuansMacbook/Downloads/Atom.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
    at /Users/JuansMacbook/Downloads/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Users/JuansMacbook/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:580:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Users/JuansMacbook/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:388:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/Users/JuansMacbook/Downloads/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:98:36)
    at HTMLDocument.<anonymous> (/Users/JuansMacbook/Downloads/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:3:61)
```

### Commands

```
     -4:14 core:save (atom-text-editor.editor.is-focused)
     -4:02.6.0 application:new-file (atom-text-editor.editor.is-focused)
     -3:58.3.0 core:save (atom-text-editor.editor.is-focused)
     -3:49.1.0 application:new-file (atom-text-editor.editor.is-focused)
     -3:46.6.0 core:save (atom-text-editor.editor.is-focused)
     -3:26.7.0 application:new-file (ul.list-inline.tab-bar.inset-panel)
  3x -3:25.3.0 core:save (atom-text-editor.editor.is-focused)
     -2:54.5.0 application:new-file (atom-text-editor.editor.is-focused)
     -2:53.4.0 core:save (atom-text-editor.editor.is-focused)
     -2:38.5.0 tree-view:add-file (span.name.icon.icon-file-directory)
  2x -2:35.1.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -2:33.3.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -2:17.6.0 core:paste (atom-text-editor.editor.is-focused)
  2x -2:17.1.0 core:save (atom-text-editor.editor.is-focused)
  2x -2:03.5.0 settings-view:check-for-package-updates (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-seti-syntax.theme-seti-ui)
  2x -0:06.9.0 core:save (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "atom-jshint",
      "linter-jshint",
      "language-javascript-jsx"
    ],
    "themes": [
      "seti-ui",
      "seti-syntax"
    ]
  },
  "linter-jscs": {
    "fixOnSave": true
  }
}
```

### Installed Packages

```coffee
# User
atom-fix-path, v0.1.0
browser-plus, v0.0.60
linter, v1.11.4
linter-jscs, v4.0.3
merge-conflicts, v1.4.4
seti-syntax, v1.0.1
seti-ui, v1.3.1
terminal-plus, v0.14.5

# Dev
No dev packages
```

**Comment by Arcanemagus** [comment] 2016-06-08 23:27
Duplicate of #257.

I'm not entirely sure what is wrong with your `package.json` and/or `.jscsrc` file from the error... it almost looks like it's empty?

**Closed by Arcanemagus** 2016-06-08 23:27 UTC
