### ISSUE TITLE
Uncaught Error: Parse error on line 8:...": "node app.js",  },  "author": "", -----------------...

### ISSUE THREAD

**Issue by ruraj** [AtomLinter/linter-jscs#256] opened 2016-05-27 04:53 UTC
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.7.4
**System**: linux 4.5.4-1-ARCH
**Thrown From**: [linter-jscs](https://github.com/AtomLinter/linter-jscs) package, v4.0.2

### Stack Trace

Uncaught Error: Parse error on line 8:
...": "node app.js",  },  "author": "", 
----------------------^
Expecting 'STRING', got '}'

```
At /usr/share/atom/resources/app.asar/src/pane.js:1002

Error: Parse error on line 8:
...": "node app.js",  },  "author": "", 
----------------------^
Expecting 'STRING', got '}'
    at Object.parseError (/home/ruraj/.atom/packages/linter-jscs/node_modules/jscs/node_modules/jsonlint/lib/jsonlint.js:55:11)
    at Object.parse (/home/ruraj/.atom/packages/linter-jscs/node_modules/jscs/node_modules/jsonlint/lib/jsonlint.js:132:22)
    at exports.parse (/home/ruraj/.atom/packages/linter-jscs/node_modules/jscs/node_modules/jsonlint/lib/jsonlint.js:417:53)
    at Object.exports.getContent (/home/ruraj/.atom/packages/linter-jscs/node_modules/jscs/lib/cli-config.js:81:27)
    at Object.<anonymous> (/home/ruraj/.atom/packages/linter-jscs/node_modules/jscs/lib/cli-config.js:142:31)
    at /home/ruraj/.atom/packages/linter-jscs/node_modules/jscs/lib/cli-config.js:36:24
    at Array.filter (native)
    at findup (/home/ruraj/.atom/packages/linter-jscs/node_modules/jscs/lib/cli-config.js:32:25)
    at Object.exports.load (/home/ruraj/.atom/packages/linter-jscs/node_modules/jscs/lib/cli-config.js:140:9)
    at Function.getConfig (/home/ruraj/.atom/packages/linter-jscs/src/linter-jscs.js:237:27)
    at /home/ruraj/.atom/packages/linter-jscs/src/linter-jscs.js:104:31
    at Function.module.exports.Emitter.simpleDispatch (/usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at TextBuffer.module.exports.TextBuffer.saveAs (/usr/share/atom/resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1091:20)
    at TextBuffer.module.exports.TextBuffer.save (/usr/share/atom/resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1083:19)
    at TextEditor.module.exports.TextEditor.save (/usr/share/atom/resources/app.asar/src/text-editor.js:660:26)
    at Pane.module.exports.Pane.saveItem (/usr/share/atom/resources/app.asar/src/pane.js:718:18)
    at Pane.module.exports.Pane.saveActiveItem (/usr/share/atom/resources/app.asar/src/pane.js:701:19)
    at Workspace.module.exports.Workspace.saveActivePaneItem (/usr/share/atom/resources/app.asar/src/workspace.js:684:35)
    at atom-workspace.commandRegistry.add.core:save (/usr/share/atom/resources/app.asar/src/register-default-commands.js:214:32)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app.asar/src/command-registry.js:260:29)
    at /usr/share/atom/resources/app.asar/src/command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/usr/share/atom/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:580:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/usr/share/atom/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:388:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/usr/share/atom/resources/app.asar/src/window-event-handler.js:98:36)
    at HTMLDocument.<anonymous> (/usr/share/atom/resources/app.asar/src/window-event-handler.js:3:61)
```

### Commands

```
     -2:05.3.0 core:backspace (atom-text-editor.editor.vim-mode.is-focused.insert-mode)
     -2:03.3.0 editor:delete-to-beginning-of-word (atom-text-editor.editor.vim-mode.is-focused.insert-mode)
     -1:56.7.0 core:backspace (atom-text-editor.editor.vim-mode.is-focused.insert-mode)
  3x -1:56.5.0 editor:delete-to-beginning-of-word (atom-text-editor.editor.vim-mode.is-focused.insert-mode)
  2x -1:55.2.0 core:backspace (atom-text-editor.editor.vim-mode.is-focused.insert-mode)
     -1:50.4.0 core:move-up (atom-text-editor.editor.vim-mode.is-focused.insert-mode)
     -1:48.9.0 editor:move-to-end-of-screen-line (atom-text-editor.editor.vim-mode.is-focused.insert-mode)
     -1:47.2.0 core:move-down (atom-text-editor.editor.vim-mode.is-focused.insert-mode)
     -1:44.5.0 vim-mode:activate-normal-mode (atom-text-editor.editor.vim-mode.is-focused.insert-mode)
  2x -1:44.1.0 vim-mode:move-down (atom-text-editor.editor.vim-mode.is-focused.normal-mode)
  2x -1:42.3.0 core:save (atom-text-editor.editor.vim-mode.is-focused.normal-mode)
     -1:00.3.0 settings-view:open (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
     -0:58.3.0 editor:delete-to-beginning-of-word (atom-text-editor.editor.mini.is-focused)
  2x -0:46.9.0 core:save (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
     -0:29.8.0 settings-view:open (atom-text-editor.editor.vim-mode.insert-mode.is-focused)
     -0:00.5.0 core:save (atom-text-editor.editor.vim-mode.insert-mode.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "one-light-ui",
      "solarized-light-syntax"
    ]
  },
  "linter-jscs": {}
}
```

### Installed Packages

```coffee
# User
file-icons, v1.7.12
linter, v1.11.4
linter-jscs, v4.0.2
minimap, v4.24.2
pigments, v0.27.1
project-manager, v2.9.7
terminal-plus, v0.14.5
vim-mode, v0.65.1

# Dev
No dev packages
```

**Comment by Arcanemagus** [comment] 2016-05-27 16:44
You have an invalid `.jscsrc` file, looks like a trailing comma snuck in there. Marking this as a duplicate of #257, since it seems the other issue where better handling of that message was discussed is closed now.

**Closed by Arcanemagus** 2016-05-27 16:44 UTC
Labels: duplicate
