### ISSUE TITLE
Additional Rules not supported

### ISSUE THREAD

**Issue by ajdaniel** [AtomLinter/linter-jscs#108] opened 2015-09-16 10:48 UTC
I can't find any documentation anywhere about whether linter-jscs supports additionalRules. Currently my project has about 6 custom rules and each one triggers an Error saying 'Unsupported rule'.

Is this being fixed? Is there intention? If not, I might try and look into this personally.

**Comment by ajdaniel** [comment] 2015-09-16 10:59
Something changed. I just updated to linter-jscs 3.0.0 and now the names are not even showing

![image](https://cloud.githubusercontent.com/assets/867941/9902961/50d798fa-5c6a-11e5-8997-53e90b01dac5.png)

**Comment by ajdaniel** [comment] 2015-09-16 11:01
Got a feeling this might all be part of https://github.com/jscs-dev/node-jscs and not here. Please close if so

**Comment by casesandberg** [comment] 2016-01-14 20:28
Yes, it is `node-jscs`, however it looks like they added in support with version `2.5.0` in October. 

Can you try again and let me know if it is still an issue?

**Comment by casesandberg** [comment] 2016-02-02 18:57
Marking as closed as I can not reproduce this. If you are still having issues please re-open.

**Closed by casesandberg** 2016-02-02 18:57 UTC
Labels: can't reproduce
