### ISSUE TITLE
Uncaught Error: Parse error on line 30:...ack": "^1.12.13",  },  "dependencies":---------------...

### ISSUE THREAD

**Issue by jose4125** [AtomLinter/linter-jscs#264] opened 2016-06-07 02:31 UTC
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.8.0
**System**: Mac OS X 10.11.5
**Thrown From**: [linter-jscs](https://github.com/AtomLinter/linter-jscs) package, v4.0.3

### Stack Trace

Uncaught Error: Parse error on line 30:
...ack": "^1.12.13",  },  "dependencies":
----------------------^
Expecting 'STRING', got '}'

```
At /Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:1002

Error: Parse error on line 30:
...ack": "^1.12.13",  },  "dependencies":
----------------------^
Expecting 'STRING', got '}'
    at Object.parseError (/Users/joslomba/.atom/packages/linter-jscs/node_modules/jscs/node_modules/jsonlint/lib/jsonlint.js:55:11)
    at Object.parse (/Users/joslomba/.atom/packages/linter-jscs/node_modules/jscs/node_modules/jsonlint/lib/jsonlint.js:132:22)
    at exports.parse (/Users/joslomba/.atom/packages/linter-jscs/node_modules/jscs/node_modules/jsonlint/lib/jsonlint.js:417:53)
    at Object.exports.getContent (/Users/joslomba/.atom/packages/linter-jscs/node_modules/jscs/lib/cli-config.js:81:27)
    at Object.<anonymous> (/Users/joslomba/.atom/packages/linter-jscs/node_modules/jscs/lib/cli-config.js:142:31)
    at /Users/joslomba/.atom/packages/linter-jscs/node_modules/jscs/lib/cli-config.js:36:24
    at Array.filter (native)
    at findup (/Users/joslomba/.atom/packages/linter-jscs/node_modules/jscs/lib/cli-config.js:32:25)
    at Object.exports.load (/Users/joslomba/.atom/packages/linter-jscs/node_modules/jscs/lib/cli-config.js:140:9)
    at Function.getConfig (/Users/joslomba/.atom/packages/linter-jscs/src/linter-jscs.js:237:27)
    at /Users/joslomba/.atom/packages/linter-jscs/src/linter-jscs.js:104:31
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at TextBuffer.module.exports.TextBuffer.saveAs (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1091:20)
    at TextBuffer.module.exports.TextBuffer.save (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1083:19)
    at TextEditor.module.exports.TextEditor.save (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:660:26)
    at Pane.module.exports.Pane.saveItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:718:18)
    at Pane.module.exports.Pane.saveActiveItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:701:19)
    at Workspace.module.exports.Workspace.saveActivePaneItem (/Applications/Atom.app/Contents/Resources/app.asar/src/workspace.js:684:35)
    at atom-workspace.commandRegistry.add.core:save (/Applications/Atom.app/Contents/Resources/app.asar/src/register-default-commands.js:214:32)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:580:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:388:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:98:36)
    at HTMLDocument.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:3:61)
```

### Commands

```
     -0:27.2.0 docblockr:parse-enter (atom-text-editor.editor.is-focused)
     -0:27.2.0 editor:newline (atom-text-editor.editor.is-focused)
     -0:26.7.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:23.9.0 docblockr:parse-enter (atom-text-editor.editor.is-focused)
     -0:23.9.0 editor:newline (atom-text-editor.editor.is-focused)
     -0:23.4.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:10.4.0 docblockr:parse-enter (atom-text-editor.editor.is-focused)
     -0:10.4.0 editor:newline (atom-text-editor.editor.is-focused)
     -0:09.7.0 core:backspace (atom-text-editor.editor.is-focused)
 10x -0:01.2.0 core:save (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "opened-files",
      "tree-view-open-files"
    ],
    "themes": [
      "atom-material-ui",
      "oceanic-next"
    ]
  },
  "linter-jscs": {
    "esnext": true,
    "preset": "google"
  }
}
```

### Installed Packages

```coffee
# User
Stylus, v3.0.0
angular-jonpapa-snippets, v0.7.0
atom-beautify, v0.29.7
atom-material-ui, v1.2.13
atom-typescript, v8.11.0
color-picker, v2.1.1
compare-files, v0.6.2
css-color-underline, v1.0.1
docblockr, v0.7.3
emmet, v2.4.3
file-icons, v1.7.13
highlight-selected, v0.11.2
language-aspx, v0.4.0
language-babel, v2.26.2
language-ejs, v0.2.0
language-riot-tag, v0.2.2
less-than-slash, v0.13.0
linter, v1.11.4
linter-jscs, v4.0.3
linter-jshint, v2.1.0
linter-lesshint, v1.5.0
linter-sass-lint, v1.5.0
markdown-format, v2.5.1
merge-conflicts, v1.4.3
motepair, v0.21.0
oceanic-next, v0.1.2
tabs-to-spaces, v1.0.2
trailing-spaces, v0.3.2
travis-ci-status, v1.1.1

# Dev
No dev packages
```

**Comment by Arcanemagus** [comment] 2016-06-07 17:00
Duplicate of #257.

It looks like you have a trailing comma somewhere in your `package.json`.

**Closed by Arcanemagus** 2016-06-07 17:00 UTC
