### ISSUE TITLE
It tries to lint even when there is no `.jscsrc` file

### ISSUE THREAD

**Issue by erykpiast** [AtomLinter/linter-jscs#196] opened 2016-02-25 14:16 UTC
### Version
3.5.7 (Atom 1.6.0-beta5)

### Issue
I have "Only config" option checked, but after the last update JSCS started to try linting my files even if there is no `.jscsrc` in my current directory tree. I think the important fact may be, that I'm using [Project Manager plugin](https://atom.io/packages/project-manager) and I have such config in other root directories inside the project, but until today it was not a problem...

**Comment by bob-v-t** [comment] 2016-02-25 15:55
Same thing here.

linter-jscs 3.4.7, Atom 1.5.3.

Running Ubuntu 15.10.

**Comment by casesandberg** [comment] 2016-02-25 16:22
Ah, thats not good. I must have broken something last night. Looking into this

**Comment by casesandberg** [comment] 2016-02-25 16:30
I am trying to reproduce this, but cant seem to. This is what I tried:

- enable `Fix on save`
- enable `Only Config`

Then I remove the `.jscsrc` file from my root. When going back to the file and saving nothing happens.

**Comment by casesandberg** [comment] 2016-02-25 16:36
Ah, found the error. Fixing.

**Comment by bob-v-t** [comment] 2016-02-25 18:22
OK, good!

**Comment by erykpiast** [comment] 2016-02-25 21:07
Thank you!

**Comment by Arcanemagus** [comment] 2016-02-25 22:26
Fix published in v3.4.8. :tada:

**Comment by joseph-turner** [comment] 2016-03-15 17:30
Reopen please. v3.4.9 seems to have broken this option again. Looks like it might be using a preset config even when a project config is not present and the option "Only Config" is checked.

**Comment by Arcanemagus** [comment] 2016-03-15 22:19
A PR fixing this would be welcome, @casesandberg hasn't been responding the last few days and I'm not going to have time till later tonight.

**Comment by casesandberg** [comment] 2016-03-15 22:50
Apologies for the slow response, I have been moving across the country. I wont be able to get to fixing this until the weekend.

**Comment by Arcanemagus** [comment] 2016-03-15 22:57
No worries, just hadn't heard from you for a while :wink:

I'll try to get this taken care of tonight.

**Comment by jtokoph** [comment] 2016-03-17 22:17
The issue is a new `getConfig` function that is returning a default config even if one doesn't exist:
https://github.com/AtomLinter/linter-jscs/pull/201/files#diff-e28d3c47e8ffe35e339a0f7ea8749700R207

**Comment by Arcanemagus** [comment] 2016-03-17 22:42
The function isn't new @jtokoph, just logic that was duplicated into multiple places (and caused a bug when something wasn't fixed in the fixOnSave part...) was pulled into there in v3.4.9.

I haven't had time yet to fix this, should be something as simple as copying [this check](https://github.com/AtomLinter/linter-jscs/blob/v3.4.9/src/linter-jscs.js#L224) right [here](https://github.com/AtomLinter/linter-jscs/blob/v3.4.9/src/linter-jscs.js#L204) so that `getConfig()` returns returns `undefined` if the option is enabled and no config was found. That check could then be replaced with just `if (!config)` in the two places it is currently.

**Comment by jtokoph** [comment] 2016-03-17 23:09
See #204 for a fix as you described.

**Closed** 2016-03-18 07:53 UTC
Labels: in progress

**Comment by mansona** [comment] 2016-09-19 20:42
Has this raised it's head again? I'm getting JSCS notifications with Only Config ticked on version 4.0.5

https://cloudup.com/cjpCvx1cFwl
https://cloudup.com/cPX_U28Q08N

**Comment by Arcanemagus** [comment] 2016-09-19 20:56
@mansona Are you sure you don't have a configuration file in any _parent_ directories? If you can't find one please file a new issue.

**Comment by mansona** [comment] 2016-09-19 22:24
@Arcanemagus yep that was it! I think a yeoman generator went a bit haywire 😖
