### ISSUE TITLE
Exception prevents file from being saved

### ISSUE THREAD

**Issue by viki53** [AtomLinter/linter-jscs#266] opened 2016-06-13 15:24 UTC
### Version

4.0.3

### Issue

I just started working on a WordPress project and copied my `.jscsrc` file from a Jekyll project 

I get the following error when I try to save a file (which doesn't get saved) or almost every time I type something in Atom:

**Atom Version**: 1.8.0
**System**: elementary OS
**Thrown From**: [linter-jscs](https://github.com/AtomLinter/linter-jscs) package, v4.0.3

### Stack Trace

Uncaught Error: Parse error on line 1:

Expecting 'STRING', 'NUMBER', 'NULL', 'TRUE', 'FALSE', '{', '[', got 'EOF'

```
At /usr/share/atom/resources/app.asar/src/pane.js:1002

Error: Parse error on line 1:

^
Expecting 'STRING', 'NUMBER', 'NULL', 'TRUE', 'FALSE', '{', '[', got 'EOF'
    at Object.parseError (/home/corentin/.atom/packages/linter-jscs/node_modules/jscs/node_modules/jsonlint/lib/jsonlint.js:55:11)
    at Object.parse (/home/corentin/.atom/packages/linter-jscs/node_modules/jscs/node_modules/jsonlint/lib/jsonlint.js:132:22)
    at exports.parse (/home/corentin/.atom/packages/linter-jscs/node_modules/jscs/node_modules/jsonlint/lib/jsonlint.js:417:53)
    at Object.exports.getContent (/home/corentin/.atom/packages/linter-jscs/node_modules/jscs/lib/cli-config.js:81:27)
    at Object.<anonymous> (/home/corentin/.atom/packages/linter-jscs/node_modules/jscs/lib/cli-config.js:142:31)
    at /home/corentin/.atom/packages/linter-jscs/node_modules/jscs/lib/cli-config.js:36:24
    at Array.filter (native)
    at findup (/home/corentin/.atom/packages/linter-jscs/node_modules/jscs/lib/cli-config.js:32:25)
    at Object.exports.load (/home/corentin/.atom/packages/linter-jscs/node_modules/jscs/lib/cli-config.js:140:9)
    at Function.getConfig (/home/corentin/.atom/packages/linter-jscs/src/linter-jscs.js:237:27)
    at /home/corentin/.atom/packages/linter-jscs/src/linter-jscs.js:104:31
    at Function.module.exports.Emitter.simpleDispatch (/usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at TextBuffer.module.exports.TextBuffer.saveAs (/usr/share/atom/resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1091:20)
    at TextBuffer.module.exports.TextBuffer.save (/usr/share/atom/resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1083:19)
    at TextEditor.module.exports.TextEditor.save (/usr/share/atom/resources/app.asar/src/text-editor.js:660:26)
    at Pane.module.exports.Pane.saveItem (/usr/share/atom/resources/app.asar/src/pane.js:718:18)
    at Pane.module.exports.Pane.saveActiveItem (/usr/share/atom/resources/app.asar/src/pane.js:701:19)
    at Workspace.module.exports.Workspace.saveActivePaneItem (/usr/share/atom/resources/app.asar/src/workspace.js:684:35)
    at atom-workspace.commandRegistry.add.core:save (/usr/share/atom/resources/app.asar/src/register-default-commands.js:214:32)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app.asar/src/command-registry.js:260:29)
    at /usr/share/atom/resources/app.asar/src/command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/usr/share/atom/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:580:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/usr/share/atom/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:388:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/usr/share/atom/resources/app.asar/src/window-event-handler.js:98:36)
    at HTMLDocument.<anonymous> (/usr/share/atom/resources/app.asar/src/window-event-handler.js:3:61)
```

### Commands

```
  2x -2:12.3.0 platformio-ide-terminal:status-pink (i.icon.icon-terminal)
     -2:03.7.0 platformio-ide-terminal:status-cyan (i.icon.icon-terminal)
     -1:11 settings-view:open (atom-text-editor.editor)
     -1:10.7.0 tree-view:reveal-active-file (atom-workspace.workspace.scrollbars-visible-always.theme-atom-material-syntax.theme-atom-material-ui)
     -0:56.2.0 tree-view:add-file (div.header.list-item)
     -0:52.8.0 core:confirm (atom-text-editor.editor.mini.is-focused)
  2x -0:52.6.0 tree-view:reveal-active-file (atom-workspace.workspace.scrollbars-visible-always.theme-atom-material-syntax.theme-atom-material-ui)
     -0:52 core:paste (atom-text-editor.editor.is-focused)
     -0:49.4.0 core:save (atom-text-editor.editor.is-focused)
     -0:34.3.0 tree-view:add-file (div.header.list-item)
     -0:31.6.0 core:confirm (atom-text-editor.editor.mini.is-focused)
  2x -0:31.5.0 tree-view:reveal-active-file (atom-workspace.workspace.scrollbars-visible-always.theme-atom-material-syntax.theme-atom-material-ui)
     -0:31.1.0 core:paste (atom-text-editor.editor.is-focused)
     -0:30.5.0 core:save (atom-text-editor.editor.is-focused)
  5x -0:28.8.0 tree-view:reveal-active-file (atom-workspace.workspace.scrollbars-visible-always.theme-atom-material-syntax.theme-atom-material-ui)
     -0:01.2.0 core:save (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "linter-sass-lint",
      "linter-stylelint"
    ],
    "excludeVcsIgnoredPaths": false,
    "ignoredNames": [
      ".git",
      ".hg",
      ".svn",
      ".DS_Store",
      "._*",
      "Thumbs.db",
      ".sass-cache"
    ],
    "packagesWithKeymapsDisabled": [
      "tree-view"
    ],
    "projectHome": "~/carbip",
    "themes": [
      "atom-material-ui",
      "atom-material-syntax"
    ]
  },
  "linter-jscs": {
    "onlyConfig": true
  }
}
```

### Installed Packages

```coffee
# User
angularjs, v0.3.4
atom-beautify, v0.28.28
atom-material-syntax, v0.4.6
atom-material-ui, v0.8.1
auto-reveal-in-sidebar, v0.8.0
emmet, v2.4.3
highlight-selected, v0.11.2
jshint, v1.8.5
linter, v1.11.8
linter-jscs, v4.0.3
minimap, v4.24.4
nav-panel, v0.0.11
platformio-ide-terminal, v2.0.10
remember-file-positions, v0.2.2
remember-folds, v0.1.0
synced-sidebar, v0.4.3
tool-bar, v0.4.0
tool-bar-atom, v1.5.0

# Dev
No dev packages
```

---

The original `.jscsrc` file in the Jekyll project was in the root folder of the project, but in this new project, it's now in a subdirectory (theme folder)

**Comment by Arcanemagus** [comment] 2016-06-13 17:17
Marking as a duplicate of #257.

I've only seen this particular message style once before, my best guess is that you have an _empty_ `package.json` (or `.jscsrc`) file, either way the JSON linter built into `jscs` that it runs on configuration files is what is complaining here.

**Closed by Arcanemagus** 2016-06-13 17:17 UTC

**Comment by viki53** [comment] 2016-06-14 07:58
I have both files, which are identical to those I copied from the other project.

The only difference I see is that they're not in the root folder of the project.
