### ISSUE TITLE
Processor at 100% of usage

### ISSUE THREAD

**Issue by catacs** [AtomLinter/linter-jscs#241] opened 2016-05-10 08:36 UTC
### Version
4.0.0

#### Atom version
1.7.3

### Issue
Produce processor 100% usage in all '*.js' files after editing a line.
![jscs_processor](https://cloud.githubusercontent.com/assets/3251397/15140291/b5c2ddfc-169a-11e6-9605-db69fa791a54.png)

![jscs_htop](https://cloud.githubusercontent.com/assets/3251397/15140290/b5c0812e-169a-11e6-9fdd-5bb9bf79d03f.png)

It ends with error #239

![jscs_error](https://cloud.githubusercontent.com/assets/3251397/15140296/be210dde-169a-11e6-93a8-c3495fbcc555.png)

**Comment by rricamar** [comment] 2016-05-10 08:56
Same here, processor at 100% while using the package

- Ubuntu `14.10 LTS`
- Atom `v1.7.3`
- Linter JSCS `v4.0.0`

**Comment by Arcanemagus** [comment] 2016-05-10 17:00
Can you post a JS file you see this on, as well as your `.jscsrc` file that affects it?

**Comment by catacs** [comment] 2016-05-11 07:43
.jscsrc
{
  preset: 'airbnb',
  requireSpacesInAnonymousFunctionExpression: {
    "beforeOpeningRoundBrace": true,
    "beforeOpeningCurlyBrace": true
  }
}

This example produces the error  #239:
example1.js
----
'use strict';

const VALUE = {color: 0x000000, x: 'fill'};
----

This example produces both #239 and the 100% cpu
example2.js
----
'use strict';
const options = { font: font, size:12, color: 0x000000 };
const data = {
  test1: {
    pages: [
      [// page 0
        {
          type:  'TEXT',
          label: 'value',
          position: { x: 411.8, y: 697.2 },
        }, {
          type:  'TEXT',
          label: 'value',
          position: { x: 411.8, y: 697.2 },
        }, {
          type:  'TEXT',
          label: 'value',
          position: { x: 411.8, y: 697.2 },
        }, {
          type:  'TEXT',
          label: 'value',
          position: { x: 411.8, y: 697.2 },
        }, {
          type:  'TEXT',
          label: 'value',
          position: { x: 411.8, y: 697.2 },
        }, {
          type:  'TEXT',
          label: 'value',
          position: { x: 411.8, y: 697.2 },
        }, {
          type:  'TEXT',
          label: 'value',
          position: { x: 411.8, y: 697.2 },
        }, {
          type:  'TEXT',
          label: 'value',
          position: { x: 411.8, y: 697.2 },
        }, {
          type:  'TEXT',
          label: 'value',
          position: { x: 411.8, y: 697.2 },
        }, {
          type:  'TEXT',
          label: 'value',
          position: { x: 411.8, y: 697.2 },
        }, {
          type:  'TEXT',
          label: 'value',
          position: { x: 411.8, y: 697.2 },
        }, {
          type:  'TEXT',
          label: 'value',
          position: { x: 411.8, y: 697.2 },
        }, {
          type:  'TEXT',
          label: 'value',
          position: { x: 411.8, y: 697.2 },
        }, {
          type:  'TEXT',
          label: 'value',
          position: { x: 411.8, y: 697.2 },
        }, {
          type:  'TEXT',
          label: 'value',
          position: { x: 411.8, y: 697.2 },
        }, {
          type:  'TEXT',
          label: 'value',
          position: { x: 411.8, y: 697.2 },
        }, {
          type:  'TEXT',
          label: 'value',
          position: { x: 411.8, y: 697.2 },
        }, {
          type:  'TEXT',
          label: 'value',
          position: { x: 411.8, y: 697.2 },
        }, {
          type:  'TEXT',
          label: 'value',
          position: { x: 411.8, y: 697.2 },
        }, {
          type:  'TEXT',
          label: 'value',
          position: { x: 411.8, y: 697.2 },
        }, {
          type:  'TEXT',
          label: 'value',
          position: { x: 411.8, y: 697.2 },
        }, {
          type:  'TEXT',
          label: 'value',
          position: { x: 411.8, y: 697.2 },
        }, {
          type:  'TEXT',
          label: 'value',
          position: { x: 411.8, y: 697.2 },
        }, {
          type:  'TEXT',
          label: 'value',
          position: { x: 411.8, y: 697.2 },
        }, {
          type:  'TEXT',
          label: 'value',
          position: { x: 411.8, y: 697.2 },
        }, {
          type:  'TEXT',
          label: 'value',
          position: { x: 411.8, y: 697.2 },
        }, {
          type:  'TEXT',
          label: 'value',
          position: { x: 411.8, y: 697.2 },
        }, {
          type:  'TEXT',
          label: 'value',
          position: { x: 411.8, y: 697.2 },
        }, {
          type:  'TEXT',
          label: 'value',
          position: { x: 411.8, y: 697.2 },
        }, {
          type:  'TEXT',
          label: 'value',
          position: { x: 411.8, y: 697.2 },
        }, {
          type:  'TEXT',
          label: 'value',
          position: { x: 411.8, y: 697.2 },
        }, {
          type:  'TEXT',
          label: 'value',
          position: { x: 411.8, y: 697.2 },
        }, {
          type:  'TEXT',
          label: 'value',
          position: { x: 411.8, y: 697.2 },
        }, {
          type:  'TEXT',
          label: 'value',
          position: { x: 411.8, y: 697.2 },
        }, {
          type:  'TEXT',
          label: 'value',
          position: { x: 411.8, y: 697.2 },
        }, {
          type:  'TEXT',
          label: 'value',
          position: { x: 411.8, y: 697.2 },
        }, {
          type:  'TEXT',
          label: 'value',
          position: { x: 411.8, y: 697.2 },
        }, {
          type:  'TEXT',
          label: 'value',
          position: { x: 411.8, y: 697.2 },
        }, {
          type:  'TEXT',
          label: 'value',
          position: { x: 411.8, y: 697.2 },
        }, {
          type:  'TEXT',
          label: 'value',
          position: { x: 411.8, y: 697.2 },
        }, {
          type:  'TEXT',
          label: 'value',
          position: { x: 411.8, y: 697.2 },
        }, {
          type:  'TEXT',
          label: 'value',
          position: { x: 411.8, y: 697.2 },
        }, {
          type:  'TEXT',
          label: 'value',
          position: { x: 411.8, y: 697.2 },
        }, {
          type:  'TEXT',
          label: 'value',
          position: { x: 411.8, y: 697.2 },
        }, {
          type:  'TEXT',
          label: 'value',
          position: { x: 411.8, y: 697.2 },
        }, {
          type:  'TEXT',
          label: 'value',
          position: { x: 411.8, y: 697.2 },
        }, {
          type:  'TEXT',
          label: 'value',
          position: { x: 411.8, y: 697.2 },
        }, {
          type:  'TEXT',
          label: 'value',
          position: { x: 411.8, y: 697.2 },
        }, {
          type:  'TEXT',
          label: 'value',
          position: { x: 411.8, y: 697.2 },
        }, {
          type:  'TEXT',
          label: 'value',
          position: { x: 411.8, y: 697.2 },
        }, {
          type:  'TEXT',
          label: 'value',
          position: { x: 411.8, y: 697.2 },
        }, {
          type:  'TEXT',
          label: 'value',
          position: { x: 411.8, y: 697.2 },
        }, {
          type:  'TEXT',
          label: 'value',
          position: { x: 411.8, y: 697.2 },
        }, {
          type:  'TEXT',
          label: 'value',
          position: { x: 411.8, y: 697.2 },
        }, {
          type:  'TEXT',
          label: 'value',
          position: { x: 411.8, y: 697.2 },
        }, {
          type:  'TEXT',
          label: 'value',
          position: { x: 411.8, y: 697.2 },
        }, {
          type:  'TEXT',
          label: 'value',
          position: { x: 411.8, y: 697.2 },
        }, {
          type:  'TEXT',
          label: 'value',
          position: { x: 411.8, y: 697.2 },
        }
      ],
      [// page 1
        {
          type:  'TEXT',
          label: 'value',
          position: { x: 411.8, y: 697.2 },
        }, {
          type:  'TEXT',
          label: 'value',
          position: { x: 411.8, y: 697.2 },
        }, {
          type:  'TEXT',
          label: 'value',
          position: { x: 411.8, y: 697.2 },
        }, {
          type:  'TEXT',
          label: 'value',
          position: { x: 411.8, y: 697.2 },
        }, {
          type:  'TEXT',
          label: function (value) {  
            const font = pdfWriter.getFontForFile(path.join(__dirname, '../../../public/fonts/raleway/Raleway-Regular.ttf'));
            if (value) {
              return true
            }
            return false
          },
          position: { x: 411.8, y: 697.2 },
        }, {
          type:  'TEXT',
          label: 'value',
          position: { x: 411.8, y: 697.2 },
        }, {
          type:  'TEXT',
          label: 'value',
          position: { x: 411.8, y: 697.2 },
        }, {
          type:  'TEXT',
          label: 'value',
          position: { x: 411.8, y: 697.2 },
        }, {
          type:  'TEXT',
          label: 'value',
          position: { x: 411.8, y: 697.2 },
        }, {
          type:  'TEXT',
          label: 'value',
          position: { x: 411.8, y: 697.2 },
        }, {
          type:  'TEXT',
          label: 'value',
          position: { x: 411.8, y: 697.2 },
        }, {
          type:  'TEXT',
          label: 'value',
          position: { x: 411.8, y: 697.2 },
        }, {
          type:  'TEXT',
          label: 'value',
          position: { x: 411.8, y: 697.2 },
        }, {
          type:  'TEXT',
          label: 'value',
          position: { x: 411.8, y: 697.2 },
        }, {
          type:  'TEXT',
          label: 'value',
          position: { x: 411.8, y: 697.2 },
        }, {
          type:  'TEXT',
          label: 'value',
          position: { x: 411.8, y: 697.2 },
        }, {
          type:  'TEXT',
          label: 'value',
          position: { x: 411.8, y: 697.2 },
        }, {
          type:  'TEXT',
          label: 'value',
          position: { x: 411.8, y: 697.2 },
        }, {
          type:  'TEXT',
          label: 'value',
          position: { x: 411.8, y: 697.2 },
        }, {
          type:  'TEXT',
          label: 'value',
          position: { x: 411.8, y: 697.2 },
        }, {
          type:  'TEXT',
          label: 'value',
          position: { x: 411.8, y: 697.2 },
        }, {
          type:  'TEXT',
          label: 'value',
          position: { x: 411.8, y: 697.2 },
        }, {
          type:  'TEXT',
          label: 'value',
          position: { x: 411.8, y: 697.2 },
        }, {
          type:  'TEXT',
          label: 'value',
          position: { x: 411.8, y: 697.2 },
        }, {
          type:  'TEXT',
          label: 'value',
          position: { x: 411.8, y: 697.2 },
        }, {
          type:  'TEXT',
          label: 'value',
          position: { x: 411.8, y: 697.2 },
        }, {
          type:  'TEXT',
          label: 'value',
          position: { x: 411.8, y: 697.2 },
        }, {
          type:  'TEXT',
          label: 'value',
          position: { x: 411.8, y: 697.2 },
        }, {
          type:  'TEXT',
          label: 'value',
          position: { x: 411.8, y: 697.2 },
        }, {
          type:  'TEXT',
          label: 'value',
          position: { x: 411.8, y: 697.2 },
        }, {
          type:  'TEXT',
          label: 'value',
          position: { x: 411.8, y: 697.2 },
        }, {
          type:  'TEXT',
          label: 'value',
          position: { x: 411.8, y: 697.2 },
        }, {
          type:  'TEXT',
          label: 'value',
          position: { x: 411.8, y: 697.2 },
        }, {
          type:  'TEXT',
          label: 'value',
          position: { x: 411.8, y: 697.2 },
        }, {
          type:  'TEXT',
          label: 'value',
          position: { x: 411.8, y: 697.2 },
        }, {
          type:  'TEXT',
          label: 'value',
          position: { x: 411.8, y: 697.2 },
        }, {
          type:  'TEXT',
          label: 'value',
          position: { x: 411.8, y: 697.2 },
        }, {
          type:  'TEXT',
          label: 'value',
          position: { x: 411.8, y: 697.2 },
        }, {
          type:  'TEXT',
          label: 'value',
          position: { x: 411.8, y: 697.2 },
        }, {
          type:  'TEXT',
          label: 'value',
          position: { x: 411.8, y: 697.2 },
        }, {
          type:  'TEXT',
          label: 'value',
          position: { x: 411.8, y: 697.2 },
        }, {
          type:  'TEXT',
          label: 'value',
          position: { x: 411.8, y: 697.2 },
        }, {
          type:  'TEXT',
          label: 'value',
          position: { x: 411.8, y: 697.2 },
        }, {
          type:  'TEXT',
          label: 'value',
          position: { x: 411.8, y: 697.2 },
        }, {
          type:  'TEXT',
          label: 'value',
          position: { x: 411.8, y: 697.2 },
        }, {
          type:  'TEXT',
          label: 'value',
          position: { x: 411.8, y: 697.2 },
        }, {
          type:  'TEXT',
          label: 'value',
          position: { x: 411.8, y: 697.2 },
        }, {
          type:  'TEXT',
          label: 'value',
          position: { x: 411.8, y: 697.2 },
        }, {
          type:  'TEXT',
          label: 'value',
          position: { x: 411.8, y: 697.2 },
        }, {
          type:  'TEXT',
          label: 'value',
          position: { x: 411.8, y: 697.2 },
        }, {
          type:  'TEXT',
          label: 'value',
          position: { x: 411.8, y: 697.2 },
        }, {
          type:  'TEXT',
          label: 'value',
          position: { x: 411.8, y: 697.2 },
        }, {
          type:  'TEXT',
          label: 'value',
          position: { x: 411.8, y: 697.2 },
        }, {
          type:  'TEXT',
          label: 'value',
          position: { x: 411.8, y: 697.2 },
        }, {
          type:  'TEXT',
          label: 'value',
          position: { x: 411.8, y: 697.2 },
        }, {
          type:  'TEXT',
          label: 'value',
          position: { x: 411.8, y: 697.2 },
        }, {
          type:  'TEXT',
          label: 'value',
          position: { x: 411.8, y: 697.2 },
        }, {
          type:  'TEXT',
          label: 'value',
          position: { x: 411.8, y: 697.2 },
        }
      ]
    ],
  },
    test1: {
      pages: [
        [// page 0
          {
            type:  'TEXT',
            label: 'value',
            position: { x: 411.8, y: 697.2 },
          }, {
            type:  'TEXT',
            label: 'value',
            position: { x: 411.8, y: 697.2 },
          }, {
            type:  'TEXT',
            label: 'value',
            position: { x: 411.8, y: 697.2 },
          }, {
            type:  'TEXT',
            label: 'value',
            position: { x: 411.8, y: 697.2 },
          }, {
            type:  'TEXT',
            label: 'value',
            position: { x: 411.8, y: 697.2 },
          }, {
            type:  'TEXT',
            label: 'value',
            position: { x: 411.8, y: 697.2 },
          }, {
            type:  'TEXT',
            label: 'value',
            position: { x: 411.8, y: 697.2 },
          }, {
            type:  'TEXT',
            label: 'value',
            position: { x: 411.8, y: 697.2 },
          }, {
            type:  'TEXT',
            label: 'value',
            position: { x: 411.8, y: 697.2 },
          }, {
            type:  'TEXT',
            label: 'value',
            position: { x: 411.8, y: 697.2 },
          }, {
            type:  'TEXT',
            label: 'value',
            position: { x: 411.8, y: 697.2 },
          }, {
            type:  'TEXT',
            label: 'value',
            position: { x: 411.8, y: 697.2 },
          }, {
            type:  'TEXT',
            label: 'value',
            position: { x: 411.8, y: 697.2 },
          }, {
            type:  'TEXT',
            label: 'value',
            position: { x: 411.8, y: 697.2 },
          }, {
            type:  'TEXT',
            label: 'value',
            position: { x: 411.8, y: 697.2 },
          }, {
            type:  'TEXT',
            label: 'value',
            position: { x: 411.8, y: 697.2 },
          }, {
            type:  'TEXT',
            label: 'value',
            position: { x: 411.8, y: 697.2 },
          }, {
            type:  'TEXT',
            label: 'value',
            position: { x: 411.8, y: 697.2 },
          }, {
            type:  'TEXT',
            label: 'value',
            position: { x: 411.8, y: 697.2 },
          }, {
            type:  'TEXT',
            label: 'value',
            position: { x: 411.8, y: 697.2 },
          }, {
            type:  'TEXT',
            label: 'value',
            position: { x: 411.8, y: 697.2 },
          }, {
            type:  'TEXT',
            label: 'value',
            position: { x: 411.8, y: 697.2 },
          }, {
            type:  'TEXT',
            label: 'value',
            position: { x: 411.8, y: 697.2 },
          }, {
            type:  'TEXT',
            label: 'value',
            position: { x: 411.8, y: 697.2 },
          }, {
            type:  'TEXT',
            label: 'value',
            position: { x: 411.8, y: 697.2 },
          }, {
            type:  'TEXT',
            label: 'value',
            position: { x: 411.8, y: 697.2 },
          }, {
            type:  'TEXT',
            label: 'value',
            position: { x: 411.8, y: 697.2 },
          }, {
            type:  'TEXT',
            label: 'value',
            position: { x: 411.8, y: 697.2 },
          }, {
            type:  'TEXT',
            label: 'value',
            position: { x: 411.8, y: 697.2 },
          }, {
            type:  'TEXT',
            label: 'value',
            position: { x: 411.8, y: 697.2 },
          }, {
            type:  'TEXT',
            label: 'value',
            position: { x: 411.8, y: 697.2 },
          }, {
            type:  'TEXT',
            label: 'value',
            position: { x: 411.8, y: 697.2 },
          }, {
            type:  'TEXT',
            label: 'value',
            position: { x: 411.8, y: 697.2 },
          }, {
            type:  'TEXT',
            label: 'value',
            position: { x: 411.8, y: 697.2 },
          }, {
            type:  'TEXT',
            label: 'value',
            position: { x: 411.8, y: 697.2 },
          }, {
            type:  'TEXT',
            label: 'value',
            position: { x: 411.8, y: 697.2 },
          }, {
            type:  'TEXT',
            label: 'value',
            position: { x: 411.8, y: 697.2 },
          }, {
            type:  'TEXT',
            label: 'value',
            position: { x: 411.8, y: 697.2 },
          }, {
            type:  'TEXT',
            label: 'value',
            position: { x: 411.8, y: 697.2 },
          }, {
            type:  'TEXT',
            label: 'value',
            position: { x: 411.8, y: 697.2 },
          }, {
            type:  'TEXT',
            label: 'value',
            position: { x: 411.8, y: 697.2 },
          }, {
            type:  'TEXT',
            label: 'value',
            position: { x: 411.8, y: 697.2 },
          }, {
            type:  'TEXT',
            label: 'value',
            position: { x: 411.8, y: 697.2 },
          }, {
            type:  'TEXT',
            label: 'value',
            position: { x: 411.8, y: 697.2 },
          }, {
            type:  'TEXT',
            label: 'value',
            position: { x: 411.8, y: 697.2 },
          }, {
            type:  'TEXT',
            label: 'value',
            position: { x: 411.8, y: 697.2 },
          }, {
            type:  'TEXT',
            label: 'value',
            position: { x: 411.8, y: 697.2 },
          }, {
            type:  'TEXT',
            label: 'value',
            position: { x: 411.8, y: 697.2 },
          }, {
            type:  'TEXT',
            label: 'value',
            position: { x: 411.8, y: 697.2 },
          }, {
            type:  'TEXT',
            label: 'value',
            position: { x: 411.8, y: 697.2 },
          }, {
            type:  'TEXT',
            label: 'value',
            position: { x: 411.8, y: 697.2 },
          }, {
            type:  'TEXT',
            label: 'value',
            position: { x: 411.8, y: 697.2 },
          }, {
            type:  'TEXT',
            label: 'value',
            position: { x: 411.8, y: 697.2 },
          }, {
            type:  'TEXT',
            label: 'value',
            position: { x: 411.8, y: 697.2 },
          }, {
            type:  'TEXT',
            label: 'value',
            position: { x: 411.8, y: 697.2 },
          }, {
            type:  'TEXT',
            label: 'value',
            position: { x: 411.8, y: 697.2 },
          }, {
            type:  'TEXT',
            label: 'value',
            position: { x: 411.8, y: 697.2 },
          }, {
            type:  'TEXT',
            label: 'value',
            position: { x: 411.8, y: 697.2 },
          }
        ],
        [// page 0
          {
            type:  'TEXT',
            label: 'value',
            position: { x: 411.8, y: 697.2 },
          }, {
            type:  'TEXT',
            label: 'value',
            position: { x: 411.8, y: 697.2 },
          }, {
            type:  'TEXT',
            label: 'value',
            position: { x: 411.8, y: 697.2 },
          }, {
            type:  'TEXT',
            label: 'value',
            position: { x: 411.8, y: 697.2 },
          }, {
            type:  'TEXT',
            label: function (value) {  
              const font = pdfWriter.getFontForFile(path.join(__dirname, '../../../public/fonts/raleway/Raleway-Regular.ttf'));
              if (value) {
                return true
              }
              return false
            },
            position: { x: 411.8, y: 697.2 },
          }, {
            type:  'TEXT',
            label: 'value',
            position: { x: 411.8, y: 697.2 },
          }, {
            type:  'TEXT',
            label: 'value',
            position: { x: 411.8, y: 697.2 },
          }, {
            type:  'TEXT',
            label: 'value',
            position: { x: 411.8, y: 697.2 },
          }, {
            type:  'TEXT',
            label: 'value',
            position: { x: 411.8, y: 697.2 },
          }, {
            type:  'TEXT',
            label: 'value',
            position: { x: 411.8, y: 697.2 },
          }, {
            type:  'TEXT',
            label: 'value',
            position: { x: 411.8, y: 697.2 },
          }, {
            type:  'TEXT',
            label: 'value',
            position: { x: 411.8, y: 697.2 },
          }, {
            type:  'TEXT',
            label: 'value',
            position: { x: 411.8, y: 697.2 },
          }, {
            type:  'TEXT',
            label: 'value',
            position: { x: 411.8, y: 697.2 },
          }, {
            type:  'TEXT',
            label: 'value',
            position: { x: 411.8, y: 697.2 },
          }, {
            type:  'TEXT',
            label: 'value',
            position: { x: 411.8, y: 697.2 },
          }, {
            type:  'TEXT',
            label: 'value',
            position: { x: 411.8, y: 697.2 },
          }, {
            type:  'TEXT',
            label: 'value',
            position: { x: 411.8, y: 697.2 },
          }, {
            type:  'TEXT',
            label: 'value',
            position: { x: 411.8, y: 697.2 },
          }, {
            type:  'TEXT',
            label: 'value',
            position: { x: 411.8, y: 697.2 },
          }, {
            type:  'TEXT',
            label: 'value',
            position: { x: 411.8, y: 697.2 },
          }, {
            type:  'TEXT',
            label: 'value',
            position: { x: 411.8, y: 697.2 },
          }, {
            type:  'TEXT',
            label: 'value',
            position: { x: 411.8, y: 697.2 },
          }, {
            type:  'TEXT',
            label: 'value',
            position: { x: 411.8, y: 697.2 },
          }, {
            type:  'TEXT',
            label: 'value',
            position: { x: 411.8, y: 697.2 },
          }, {
            type:  'TEXT',
            label: 'value',
            position: { x: 411.8, y: 697.2 },
          }, {
            type:  'TEXT',
            label: 'value',
            position: { x: 411.8, y: 697.2 },
          }, {
            type:  'TEXT',
            label: 'value',
            position: { x: 411.8, y: 697.2 },
          }, {
            type:  'TEXT',
            label: 'value',
            position: { x: 411.8, y: 697.2 },
          }, {
            type:  'TEXT',
            label: 'value',
            position: { x: 411.8, y: 697.2 },
          }, {
            type:  'TEXT',
            label: 'value',
            position: { x: 411.8, y: 697.2 },
          }, {
            type:  'TEXT',
            label: 'value',
            position: { x: 411.8, y: 697.2 },
          }, {
            type:  'TEXT',
            label: 'value',
            position: { x: 411.8, y: 697.2 },
          }, {
            type:  'TEXT',
            label: 'value',
            position: { x: 411.8, y: 697.2 },
          }, {
            type:  'TEXT',
            label: 'value',
            position: { x: 411.8, y: 697.2 },
          }, {
            type:  'TEXT',
            label: 'value',
            position: { x: 411.8, y: 697.2 },
          }, {
            type:  'TEXT',
            label: 'value',
            position: { x: 411.8, y: 697.2 },
          }, {
            type:  'TEXT',
            label: 'value',
            position: { x: 411.8, y: 697.2 },
          }, {
            type:  'TEXT',
            label: 'value',
            position: { x: 411.8, y: 697.2 },
          }, {
            type:  'TEXT',
            label: 'value',
            position: { x: 411.8, y: 697.2 },
          }, {
            type:  'TEXT',
            label: 'value',
            position: { x: 411.8, y: 697.2 },
          }, {
            type:  'TEXT',
            label: 'value',
            position: { x: 411.8, y: 697.2 },
          }, {
            type:  'TEXT',
            label: 'value',
            position: { x: 411.8, y: 697.2 },
          }, {
            type:  'TEXT',
            label: 'value',
            position: { x: 411.8, y: 697.2 },
          }, {
            type:  'TEXT',
            label: 'value',
            position: { x: 411.8, y: 697.2 },
          }, {
            type:  'TEXT',
            label: 'value',
            position: { x: 411.8, y: 697.2 },
          }, {
            type:  'TEXT',
            label: 'value',
            position: { x: 411.8, y: 697.2 },
          }, {
            type:  'TEXT',
            label: 'value',
            position: { x: 411.8, y: 697.2 },
          }, {
            type:  'TEXT',
            label: 'value',
            position: { x: 411.8, y: 697.2 },
          }, {
            type:  'TEXT',
            label: 'value',
            position: { x: 411.8, y: 697.2 },
          }, {
            type:  'TEXT',
            label: 'value',
            position: { x: 411.8, y: 697.2 },
          }, {
            type:  'TEXT',
            label: 'value',
            position: { x: 411.8, y: 697.2 },
          }, {
            type:  'TEXT',
            label: 'value',
            position: { x: 411.8, y: 697.2 },
          }, {
            type:  'TEXT',
            label: 'value',
            position: { x: 411.8, y: 697.2 },
          }, {
            type:  'TEXT',
            label: 'value',
            position: { x: 411.8, y: 697.2 },
          }, {
            type:  'TEXT',
            label: 'value',
            position: { x: 411.8, y: 697.2 },
          }, {
            type:  'TEXT',
            label: 'value',
            position: { x: 411.8, y: 697.2 },
          }, {
            type:  'TEXT',
            label: 'value',
            position: { x: 411.8, y: 697.2 },
          }
        ]
      ],
    },
}
----

**Comment by Arcanemagus** [comment] 2016-05-11 17:33
(Replaced that giant JS block with an uploaded zip of the same file)

As for this I can't reproduce any of the reported issues on `example1.js`, however `example2.js` shows both reported problems. The 100% CPU usage is `jscs` itself, put in some timing data and got this:
![image](https://cloud.githubusercontent.com/assets/427137/15190228/9b63c114-1763-11e6-98e2-cbc49f4375bf.png)
_Note: There is no total time reported since it is crashing with the invalid range issue._

This matches what I'm seeing on the console pretty well:
![image](https://cloud.githubusercontent.com/assets/427137/15190257/c507120a-1763-11e6-8b46-5c4b37e7c07e.png)

I'm trying to get a minimal repro case to file over on `jscs`.

**Comment by Arcanemagus** [comment] 2016-05-11 18:23
Since it was already halfway there, cleaned up the performance code and put it up in #244, after the next release if Atom is started in dev mode you will get logs similar to the above :wink:.

**Comment by Arcanemagus** [comment] 2016-05-11 18:54
Filed the above bug regarding the column (really line) bug, checking now if the CPU lockup is just related to the size/complexity of the file, or if it is another bug.

**Comment by Arcanemagus** [comment] 2016-05-11 19:53
As outlined in the above issue it looks like the performance issue is related to the `maximumLineLength` rule, it's making the CLI take almost 8 times as long to run on that file, and the Node API (from within Atom) take 33x as long.

That rule is included in the `airbnb` preset which you are using.

**Comment by epsitec** [comment] 2016-05-19 16:25
@Arcanemagus I've also come across same kind of very very slow atom editor performance (hangs for about 20 seconds on my machine) on a file which has multiple time exceeded the `maximumLineLength` rule. Setting it to `200` and thus removing any warnings makes the file editable like a breeze.

Are you (still) interested in the JavaScript source and the `.jscsrc` files?

**Comment by Arcanemagus** [comment] 2016-05-19 16:31
Unless it is different from what @catacs already reported [here](https://github.com/AtomLinter/linter-jscs/issues/241#issuecomment-218385785) there is nothing that can be done about this until https://github.com/cst/cst/issues/113 is fixed.

Well, we _could_ move this package to a worker thread module, like `linter-eslint` is setup currently. This is the ideal setup, but as it requires a lot of work and makes things more complicated nobody has worked on it (everyone that would uses `eslint` :stuck_out_tongue:). If you wanted to put up a PR for moving in that direction that would be awesome!

**Comment by epsitec** [comment] 2016-05-19 16:44
I am surprised that this `maximumLineLength` thing has anything to do  with `cst`. And I am (not yet) fluent enough in JavaScript to dare have a try at investigating why `jscs` behaves so poorly when fed with a file having many long lines (between 121 and 150 characters).

**Comment by Arcanemagus** [comment] 2016-05-19 16:48
`cst` is the parser tree used by `jscs` to build a model of your code. I'm not sure why it's listed as a _memory_ issue myself, but it's not my codebase so I'm not arguing :stuck_out_tongue:.

**Comment by Arcanemagus** [comment] 2016-07-27 21:48
Marking this as closed, all JSCS development has [stopped](http://eslint.org/blog/2016/07/jscs-end-of-life) so this will never be fixed. Either downgrade to the JSCS v2 version or preferably move to ESlint.

**Closed by Arcanemagus** 2016-07-27 21:48 UTC
Labels: External
