### ISSUE TITLE
Can't save file even with fix enabled

### ISSUE THREAD

**Issue by Megajin** [AtomLinter/linter-jscs#344] opened 2017-11-08 14:41 UTC
### Version
Tested with this versions, I know that `atom-ide-ui` and linter won't go well together I disabled them respectively to test this issue.

atom: 1.21.1
linter-jscs: 4.1.3
linter-jshint: 3.1.6
linter: 2.2.0
atom-ide-ui: 0.5.4

Like I said I disabled all packages and tried different constellations, all showed the error described below. Even when only `linter-jscs` is active the error occurs.

### Issue
When I try to save a file let's say `test.js` with  only this input: `import { test } from './anotherfile.js';` the linter goes crazy and won't save my file. The console shows this output:

```
C:\Users\myUser\.atom\packages\linter-jscs\node_modules\jsonlint\lib\jsonlint.js:55 Uncaught (in promise) Error: Parse error on line 40:
...fycss": "^1.0.8",  },  "dependencies":
----------------------^
Expecting 'STRING', got '}'
    at Object.parseError (C:\Users\myUser\.atom\packages\linter-jscs\node_modules\jsonlint\lib\jsonlint.js:55:11)
    at Object.parse (C:\Users\myUser\.atom\packages\linter-jscs\node_modules\jsonlint\lib\jsonlint.js:132:22)
    at exports.parse (C:\Users\myUser\.atom\packages\linter-jscs\node_modules\jsonlint\lib\jsonlint.js:417:53)
    at Object.exports.getContent (C:\Users\myUser\.atom\packages\linter-jscs\node_modules\jscs\lib\cli-config.js:81:27)
    at Object.<anonymous> (C:\Users\myUser\.atom\packages\linter-jscs\node_modules\jscs\lib\cli-config.js:142:31)
    at C:\Users\myUser\.atom\packages\linter-jscs\node_modules\jscs\lib\cli-config.js:36:24
    at Array.filter (native)
    at findup (C:\Users\myUser\.atom\packages\linter-jscs\node_modules\jscs\lib\cli-config.js:32:25)
    at Object.exports.load (C:\Users\myUser\.atom\packages\linter-jscs\node_modules\jscs\lib\cli-config.js:140:9)
    at getConfig (file:///C:/Users/myUser/.atom/packages/linter-jscs/src/linter-jscs.js:47:25)
    at file:///C:/Users/myUser/.atom/packages/linter-jscs/src/linter-jscs.js:185:26
    at Function.module.exports.Emitter.simpleDispatch (C:\Users\myUser\AppData\Local\atom\app-1.21.1\resources\app\node_modules\event-kit\lib\emitter.js:25:20)
    at Emitter.<anonymous> (C:\Users\myUser\AppData\Local\atom\app-1.21.1\resources\app\node_modules\event-kit\lib\emitter.js:154:50)
    at Emitter.module.exports.Emitter.emitAsync (C:\Users\myUser\AppData\Local\atom\app-1.21.1\resources\app\node_modules\event-kit\lib\emitter.js:157:18)
    at C:\Users\myUser\AppData\Local\atom\app-1.21.1\resources\app\node_modules\text-buffer\lib\text-buffer.js:1288:38
parseError	@	C:\Users\myUser\.atom\packages\linter-jscs\node_modules\jsonlint\lib\jsonlint.js:55
parse	@	C:\Users\myUser\.atom\packages\linter-jscs\node_modules\jsonlint\lib\jsonlint.js:132
exports.parse	@	C:\Users\myUser\.atom\packages\linter-jscs\node_modules\jsonlint\lib\jsonlint.js:417
exports.getContent	@	C:\Users\myUser\.atom\packages\linter-jscs\node_modules\jscs\lib\cli-config.js:81
(anonymous)	@	C:\Users\myUser\.atom\packages\linter-jscs\node_modules\jscs\lib\cli-config.js:142
(anonymous)	@	C:\Users\myUser\.atom\packages\linter-jscs\node_modules\jscs\lib\cli-config.js:36
findup	@	C:\Users\myUser\.atom\packages\linter-jscs\node_modules\jscs\lib\cli-config.js:32
exports.load	@	C:\Users\myUser\.atom\packages\linter-jscs\node_modules\jscs\lib\cli-config.js:140
getConfig	@	linter-jscs.js:47
(anonymous)	@	linter-jscs.js:185
module.exports.Emitter.simpleDispatch	@	<embedded>:64158
(anonymous)	@	<embedded>:64287
module.exports.Emitter.emitAsync	@	<embedded>:64290
(anonymous)	@	<embedded>:32286
```

This habbens in all `*.js` files... It doesn't matter if I use ES6 syntax or not.

Regards,
Megajin
#

**Comment by Arcanemagus** [comment] 2019-10-07 18:28
Duplicate of #430

**Closed by Arcanemagus** 2019-10-07 18:28 UTC
