### ISSUE TITLE
Can't use custom file as a preset

### ISSUE THREAD

**Issue by justinaray** [AtomLinter/linter-jscs#111] opened 2015-09-18 18:53 UTC
# tl/dr;

package.json defines a `jscsConfig` object with a `preset` option pointed to a file in my project.  I get a `AssertionError: Preset "" does not exist` error popup.  I think this is due to the fact that my preset 'label' does not match one of the pre-defined presets.

# Background

Using a package that has jscs defaults and overrides with .jscsrc.  Need to point to a higher order file that  includes both files to get equivalent atom linting as I am seeing CLI with this package.

**Comment by swaj** [comment] 2015-12-07 21:48
+1, happening to me too.

**Comment by casesandberg** [comment] 2016-01-14 23:14
So if I understand correctly, this package is registering jscs defaults and then you are registering rules in `.jscsrc` and because you are using the file it is using those settings in replace defaults and you are looking for a solution that merges the default settings with your `.jscsrc` file?

**Comment by casesandberg** [comment] 2016-02-02 19:09
Marking as closed as I can not reproduce this. If you are still having issues please re-open.

**Closed by casesandberg** 2016-02-02 19:09 UTC
Labels: need more info
